### ISSUE TITLE
Add forecast_date, target_end_date to COVIDhub-ensemble forecasts from 2020-04-13 and 2020-04-27

### ISSUE THREAD

**Issue by jarad** [reichlab/covid19-forecast-hub#100]
These files need `forecast_date` and `target_end_date`:

https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/COVIDhub-ensemble/2020-04-13-COVIDhub-ensemble.csv
https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/COVIDhub-ensemble/2020-04-27-COVIDhub-ensemble.csv

related to #99

**Comment by nickreich** [comment]
also remove information csv from data-processed/COVIDhub-ensemble
