### ISSUE TITLE
Data missing from visualization

### ISSUE THREAD

**Issue by RobertWalraven** [reichlab/covid19-forecast-hub#1020]
This is the second week in a row that my model is shown as being eligible in all categories but is not included in the visualization at covid19forecasthub.org.   Is there something else I need to do to get included?

**Comment by hannanabdul55** [comment]
Sorry about this. We had removed this earlier to investigate why it was breaking our visualization. It was a small change that was causing the issue. I fixed this in all your existing forecasts in the repository. For all new forecasts, could you also make sure you use all lowercase letters `point` and `quantile` in the `type column? Thank you! 
Also, Fixed this and deployed on the hub. It should be live now!

**Comment by RobertWalraven** [comment]
Ah, the curse of us old school programmers who like to capitalize words.  Glad you were able to catch the problem.  The forecast is generated programmatically, so the fix is a simple edit.   Thanks for tracking the problem down!
