### ISSUE TITLE
update wiki page on truth data

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#1023]
https://github.com/reichlab/covid19-forecast-hub/wiki/Truth-Data

**Comment by jarad** [comment]
I've added content on the NYTimes and USAFacts and adjusted JHU discussion accordingly.

**Comment by jarad** [comment]
It is unclear to me what 'This includes some "county-level" records for which we do not request forecasts.' means. Is this an old statement from when we did not request county forecasts?

**Comment by elray1** [comment]
It's referring to the cases assigned to 5-digit fips codes described more in the following two sentences: "These are records with a five-digit FIPS code beginning with 80 or 90, corresponding to "Out of State" or "Unassigned" locations. For this reason, the counts at the state level may in general be larger than the sum of the counts for the counties within a given state."  Feel free to revise for clarity.
