### ISSUE TITLE
add incident death targets (1-4 week ahead) to visualization

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#108]

**Comment by katiehouse3** [comment]
My checklist for making this work:
- [ ] Get d3-foresight code to work locally
- [ ] Adapt script to use output of d3-foresight
- [ ] Edit d3-foresight to be same as current visualization
- [ ] Add new targets to parse-data
- [ ] Add new dropdown for targets
- [ ] Select new targets with dropdown
