### ISSUE TITLE
change ensemble model_designation to primary

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#1086]

**Comment by elray1** [comment]
just to be safe, maybe we should force its status to "other" in ensembles code?  and as part of that, maybe put the code to get status from metadata files into a function in `covidEnsembles` (this code is in both the plot_forecasts file and the build_ensemble file).

**Comment by hannanabdul55** [comment]
I think we can keep it as `other` itself right now.  I have added code to specifically include the ensemble right now.

**Comment by nickreich** [comment]
It would be nice to switch it to `primary` as that is a reflection of its true designation. So I think we would need to coordinate with the ensemble package to explicitly exclude it. If we switched it to `primary` would it be ok with the visualization code? @hannanabdul55

**Comment by hannanabdul55** [comment]
Yes. It would be okay in the visualization code.

**Comment by hannanabdul55** [comment]
Made this change in https://github.com/reichlab/covid19-forecast-hub/pull/1088/commits/dfd129d9be00f3875a7763c9dbd0134e495e826a . 
Change is part of #1088

**Comment by elray1** [comment]
@nickreich While we're thinking about this, what designation should we use for the baseline model?

**Comment by nickreich** [comment]
are we currently including it in the ensemble? if not, seems like "other" would be appropriate. if so, then "secondary". or we could reconsider our decision to include/not.

**Comment by elray1** [comment]
The covidEnsembles dependency is resolved by 009c831.  Sounds like we should change COVIDhub-baseline to "secondary", then close this issue.
