### ISSUE TITLE
add longer horizons to Zoltar death truth data.

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#1091]
Right now, Zoltar only has 1 through 4 week ahead scores for cum and inc death targets. Since we accept submissions of up to 20 weeks, we should be able to score those submissions. Is this an issue with what data is submitted in the truth data?

**Comment by hannanabdul55** [comment]
Just ran the Zoltar truth data script for 20 week ahead and it seemed to work fine. I can make this change in the hub.

**Comment by nickreich** [comment]
Great. We should check with @matthewcornell to make sure that this won't add additional undue strain to Zoltar...

**Comment by hannanabdul55** [comment]
Just a comparison on the size for the 2 csvs: 
- CSV with 4 wk ahead:  https://github.com/reichlab/covid19-forecast-hub/blob/master/data-truth/zoltar-truth.csv
  - Size - 2.26MB
  - Entries - `58420` rows. 
- CSV with 20 wk ahead: https://github.com/reichlab/covid19-forecast-hub/blob/update-wk-ahead-zoltar-truth/data-truth/zoltar-truth.csv
  -  Size - 7.15MB. 
  - Entries - `183540` rows.

**Comment by matthewcornell** [comment]
I'd say go for it and see how it goes.

**Comment by nickreich** [comment]
@matthewcornell will re-visit this once the issue mentioned above about score querying is resolved, to see whether this push will be ok.

**Comment by matthewcornell** [comment]
I the large truth file locally and then ran scoring, and I saw no issues. Best I could tell, there were only a few thousand more score rows than before, which IIRC makes sense given that most models only forecast up to 4 weeks out, correct? If I'm right about that, then I think we can go ahead and upload the larger truth file to production. Unless I'm missing something? I ran a few score queries locally, and they ran fine.

**Comment by nickreich** [comment]
Great, let's push it.

**Comment by hannanabdul55** [comment]
@matthewcornell @nickreich  done in #1423

**Comment by matthewcornell** [comment]
I approved the PR, @hannanabdul55
