### ISSUE TITLE
20-week projection is too big for github

### ISSUE THREAD

**Issue by RobertWalraven** [reichlab/covid19-forecast-hub#1108]
I created a 20-week projection per your latest changes.   The file was 38 MB but Github only allows files under 25 MB.   What do you suggest?   Send it in parts, or cut back to fewer weeks ahead?

**Comment by RobertWalraven** [comment]
Also node.js check does not allow more than 8 weeks.

**Comment by nickreich** [comment]
The 20 week ahead projections are only accepted for the inc/cum death targets. Does it say so elsewhere in the documentation? For case forecasts, we only accept up to 8 wk ahead. But in all cases, we encourage you to only submit forecasts that you have validated yourself and feel comfortable with their accuracy at all of the submitted horizons.

**Comment by RobertWalraven** [comment]
Got it.  However, there is still the problem of the 25 MB limit in Github, since 20-week projections of inc/cum deaths would probably exceed that limit.
