### ISSUE TITLE
add validation to ensure forecast_date in filename matches the forecast_date in columns 

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#111]
ensure
 - forecast_date is in filename
 - there is only one unique date in forecast_date column in file
 - the unique value of forecast_date within the file matches the forecast_date in filename

**Comment by jbracher** [comment]
I included this in the R validation checks.

**Comment by nickreich** [comment]
@katiehouse3 this would be nice to have in place before the Monday submissions. e.g. the current IHME PR should fail because the date in the column `2020-05-01` doesn't match the date in the filename `2020-05-04`.

**Comment by katiehouse3** [comment]
On it 👍
