### ISSUE TITLE
Invisible coloring for visualization of model forecasts

### ISSUE THREAD

**Issue by youyanggu** [reichlab/covid19-forecast-hub#1242]
Hi there, the models at the end of the list are colored white, which cause them to be invisible on the plot. See screenshot below. Could an alternate color be arranged?

<img width="1340" alt="Screen Shot 2020-08-26 at 4 44 09 PM" src="https://user-images.githubusercontent.com/1267035/91354980-7ff6c200-e7bb-11ea-8fb4-a08dde2179fc.png">

**Comment by hannanabdul55** [comment]
Will check this out. Thanks for reporting this!
