### ISSUE TITLE
automate weekly report generation

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#1247]
The weekly report is basically automatable, although does require some special R packages, etc.. What is the best way to automate this? Could we do it through GitHub actions or is something via a local make run simpler?

**Comment by eycramer** [comment]
I've never used github actions but I'm willing to try and figure it out

**Comment by hannanabdul55** [comment]
Yeah this would be cool! But I am not sure about the step instructions for R on CI. But should be relatively easy only.

**Comment by hannanabdul55** [comment]
Merged to master. You can browse the page at https://covid19forecasthub.org/reports/single_page.html
