### ISSUE TITLE
revise text above visualization

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#125]

**Comment by nickreich** [comment]
I need to write some new less specific explainer text to what the ensemble is doing

**Comment by nickreich** [comment]
Can we replace the current text with the following?

The ensemble forecast combines models unconditional on particular interventions being in place with those conditional on certain social distancing measures continuing. To ensure consistency across weeks, only models that have forecasted for 4 weeks ahead are included in the ensemble.

And please change the link of the text "ensemble forecast" to link to this file: https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/COVIDhub-ensemble/metadata-COVIDhub-ensemble.txt

**Comment by katiehouse3** [comment]
Just pushed may take 10-20 mins to update on live site 👍
