### ISSUE TITLE
check what is happening with USVI data in truth and forecasts

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#127]
do we have US Virgin Islands data in truth?

**Comment by nickreich** [comment]
@katiehouse3 CDC has commented that we don't have truth data for the USVI. We do seem to have some forecasts for them though. Is this a fixable issue with how we are importing/reading in the USVI data? 
![image](https://user-images.githubusercontent.com/1280767/80554363-e51be180-899a-11ea-9552-54020e40ca13.png)

**Comment by katiehouse3** [comment]
No problem I can add USVI 👍

**Comment by jarad** [comment]
FYI, [nytimes data](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-truth/nytimes/truth_nytimes-Cumulative%20Deaths.csv) has USVI data
