### ISSUE TITLE
automate pushing of new forecasts into zoltar

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#128]
When new forecast files are added to the repo, we would like them to be automatically pushed to Zoltar. This might require a check to see if the model exists in Zoltar first, and creating a new model if it is not there. Ideally, it'd be nice if that check was part of the formal validation. Then, if the model is not in Zoltar, even if we have to add the model manually to Zoltar, we could re-run the check when the model has been created.

**Comment by Khoale1096** [comment]
- [x] Automate creating a new model if it's not on Zoltar
- [x] Automate creating a new time zero if it's not on Zoltar
- [x] Automate pushing new forecasts to Zoltar
- [ ] Automate pushing modified forecasts to Zoltar
