### ISSUE TITLE
automate updating of ground truth data

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#129]
ground truth data should be updated locally in this repo and in Zoltar.

**Comment by katiehouse3** [comment]
Adding @Khoale1096 for help with automatic Zoltar truth data uploading

**Comment by katiehouse3** [comment]
The truth data automatically updates at every visualization update. Should I make it more frequent?

**Comment by nickreich** [comment]
Just bumping this up, as we discussed today, that truth data should update every day in the early morning. 6:30am?

**Comment by katiehouse3** [comment]
Will work on this tomorrow morning bright and early 🌞
