### ISSUE TITLE
Discrepancy between incidence and cumulative death forecasts for USACE-ERDC_SEIR

### ISSUE THREAD

**Issue by eycramer** [reichlab/covid19-forecast-hub#1310]
Hi @har96, 

We are filing this issue because we noticed that your one-week ahead forecasts of incident and cumulative deaths didn't agree with each other this week. We would expect the one-week ahead predictive median for cumulative deaths to be approximately equal to the last reported cumulative deaths plus the one-week ahead predictive median for incident deaths, but this was not the case for your forecast submitted this week. The reported cumulative deaths for the US as of Saturday August 29 was 182761, according to the data reported in the JHU CSSE repository at the end of day on Sunday August 30. The median of your submitted one week ahead forecast for cumulative deaths was 189253, which suggests a forecast of 6492 incident deaths. However, this is not in agreement with the median of the submitted one week ahead forecast for incident deaths, which was 7823.

We can imagine that this might happen for any of several reasons: for example, you may be using two different models to forecast incident and cumulative deaths, or you may be calculating cumulative deaths using a different reference data set or a different procedure for aggregating to the national level than we are (for reference, we describe our approach to calculating aggregated cumulative deaths based on the JHU CSSE data [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Truth-Data). Regardless, we wanted to bring this discrepancy to your attention in case you were not aware of it.

Our goal is to make the ensemble forecasts of incident and cumulative deaths consistent with each other. This is only possible if the submitted forecasts of incident and cumulative deaths from each model are consistent with each other. Can you please respond to this issue with a description of why there is this discrepancy and also whether you have a plan to fix it? Thanks!

**Comment by eycramer** [comment]
Hi @erdc-cv19 , 

I am following up on this because this week there is still a discrepancy this week between your incidence and cumulative death forecasts. 

The reported cumulative deaths for the US as of Saturday September 5th was 188,538, according to the data reported in the JHU CSSE repository at the end of day on Sunday September 6th. The median of your submitted one week ahead forecast for cumulative deaths was 194,406, which suggests a forecast of 5868 incident deaths. However, this is not in agreement with the median of the submitted one week ahead forecast for incident deaths, which was 7027.

Can you please respond to this issue with a description of why there is this discrepancy and also whether you have a plan to fix it? Thank you!

**Comment by erdc-cv19** [comment]
Hi,

This is definitely a problem.  We are trying to track it down now.  One question I guess we have now is that when we download the data on Monday (usually 5:30am CDT, sometimes later), the last day in the file below says 09/06, Sunday.  Are we to interpret that as truth for Saturday the 5th?

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv

--
Glover E. George, PhD
Computer Scientist
US Army Engineer Research and Development Center
Vicksburg, MS 39180
Phone: 601-634-4730
Cell: 601-336-0033
glover.e.george@erdc.dren.mil<mailto:glover.e.george@erdc.dren.mil>

**Comment by erdc-cv19** [comment]
Hi.  After review, we found two issues which could cause diverging numbers.  1.  We were assuming that data downloaded on Monday the 7th, with the last date in the file being the 6th, was truth for the 5th.  It seems that a file with the last column of the 6th is truth for the 6th, and that we should interpret the column header to be for that day.
2. We calculate our cumulative totals from the 50 us states plus DC. We do not include US territories, as our model is built from the county level up, and JHU doesn't provide (at least last time we checked) county-level data for US territories.  It is possible we could extrapolate from JHU truth, but we simply don't do that at the moment.

Please let us know if this helps.
