### ISSUE TITLE
Discrepancy between incidence and cumulative death forecasts for IHME-CurveFit

### ISSUE THREAD

**Issue by eycramer** [reichlab/covid19-forecast-hub#1314]
Hi @raym2622,

We are filing this issue because we noticed that your one-week ahead forecasts of incident and cumulative deaths didn't agree with each other this week. We would expect the one-week ahead predictive median for cumulative deaths to be approximately equal to the last reported cumulative deaths plus the one-week ahead predictive median for incident deaths, but this was not the case for your forecast submitted this week. The reported cumulative deaths for the US as of Saturday August 29 was 182761, according to the data reported in the JHU CSSE repository at the end of day on Sunday August 30. The median of your submitted one week ahead forecast for cumulative deaths was 188,531, which suggests a forecast of 5770 incident deaths. However, this is not in agreement with the median of the submitted one week ahead forecast for incident deaths, which was 6950.

We can imagine that this might happen for any of several reasons: for example, you may be using two different models to forecast incident and cumulative deaths, or you may be calculating cumulative deaths using a different reference data set or a different procedure for aggregating to the national level than we are (for reference, we describe our approach to calculating aggregated cumulative deaths based on the JHU CSSE data [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Truth-Data). Regardless, we wanted to bring this discrepancy to your attention in case you were not aware of it.

Our goal is to make the ensemble forecasts of incident and cumulative deaths consistent with each other. This is only possible if the submitted forecasts of incident and cumulative deaths from each model are consistent with each other. Can you please respond to this issue with a description of why there is this discrepancy and also whether you have a plan to fix it? Thanks!

**Comment by raym2622** [comment]
Hello Estee,

Thank you for reaching out and bringing this discrepancy to our attention!

Though I personally don't see any problem on our end as you can see here
<https://covid19.healthdata.org/united-states-of-america?view=total-deaths&tab=trend.>
from
our projections. Our most recent submission had a reported date of August
27 and the projected cumulative deaths on August 29 is 181,556 on our end
(we had no way of knowing the exact number from JHU ahead of our last run).
Our 1 week ahead mean incident forecast of deaths is 6909 in the submission
and the sum of this and 181,556 comes to 188,465, which matches the mean of
our 1 week ahead cumulative deaths in the submission.

Hope that makes sense and please let me know if I can help further in any
way!

Thanks,
Ray

**Comment by elray1** [comment]
Hi Ray -- This makes sense, thanks for the clarification.

**Comment by elray1** [comment]
We are closing this issue -- thanks for your response, which was helpful to know.
