### ISSUE TITLE
Make R validation checks runnable on a file and a directory

### ISSUE THREAD

**Issue by jarad** [reichlab/covid19-forecast-hub#132]
Now that I know about it, I find the [R validation script](https://github.com/reichlab/covid19-forecast-hub/blob/master/code/validation/perform_plausibility_checks_script.R) extremely useful. What would make it even more useful is if you could run it on a single file and on a single directory, i.e. all the files in that directory. 

The way I see this working is through two new functions 

    validate_file(file)
    validate_dir(dir)

Then the script would loop through directories calling `validate_dir()` and `validate_dir()` would loop through files calling `validate_file()`. This would allow a user to just run `validate_file()` if they are just adding a new file or `validate_dir()` if the processing script for one data source was modified and re-run on all data-raw/ files for that data source and therefore the entire directory needs to be checked.

**Comment by jarad** [comment]
Related to #106 since what I really wanted for that issue was a way to check my data in R before issuing a PR. #106 is still relevant because it would allow someone to perform the python checks before issuing a PR.

**Comment by jbracher** [comment]
Will look into this later today. There are a couple of things which are checked in Python but not the R script, so I may have to add a few things to avoid major discrepancies.

**Comment by jbracher** [comment]
Created `validate_file` and `validate_dir`, added a few checks already present in the Python version to improve coherence.
