### ISSUE TITLE
Make R validation report uniform

### ISSUE THREAD

**Issue by jarad** [reichlab/covid19-forecast-hub#138]
To make the output from running the R validation checks, can we 

1. Use "VALIDATED:" for each test that validates, e.g. "VALIDATED: filename". 
2. Make any failed test a warning(). This may already be the case. 
3. Make any helpful warnings just a message(). 

The purpose for 1. is that if you run this and see "VALIDATED:" all the way down, you are all set. As it is, it feels like you need to read each message to verify that it validated. 

The purpose for 2. and 3. is so we can let the team's know that if they receive a warning() with these validations, it will be an error in the PR.

**Comment by jarad** [comment]
@jbracher I tried to address the comments in this issue, but I'm leaving the issue open in case I broke something, i.e. made something an error that should be a warning, or a warning that should be an error, etc.

**Comment by jbracher** [comment]
Tested and added messages for checks of quantiles.
