### ISSUE TITLE
Discrepancy between incidence and cumulative death forecasts for UMich-RidgeTfReg (9/9/2020)

### ISSUE THREAD

**Issue by eycramer** [reichlab/covid19-forecast-hub#1385]
Hi @sabcorse and @scorsett, 

We are filing this issue because we noticed that your one-week ahead forecasts of incident and cumulative deaths didn't agree with each other this week. We would expect the one-week ahead predictive median for cumulative deaths to be approximately equal to the last reported cumulative deaths plus the one-week ahead predictive median for incident deaths, but this was not the case for your forecast submitted this week. The reported cumulative deaths for the US as of Saturday September 5th was 188,538, according to the data reported in the JHU CSSE repository at the end of day on Sunday September 6th. The median of your submitted one week ahead forecast for cumulative deaths was 193,863, which suggests a forecast of 5325 incident deaths. However, this is not in agreement with the median of the submitted one week ahead forecast for incident deaths, which was 7516.

We can imagine that this might happen for any of several reasons: for example, you may be using two different models to forecast incident and cumulative deaths, or you may be calculating cumulative deaths using a different reference data set or a different procedure for aggregating to the national level than we are (for reference, we describe our approach to calculating aggregated cumulative deaths based on the JHU CSSE data here. Regardless, we wanted to bring this discrepancy to your attention in case you were not aware of it.

Our goal is to make the ensemble forecasts of incident and cumulative deaths consistent with each other. This is only possible if the submitted forecasts of incident and cumulative deaths from each model are consistent with each other. Can you please respond to this issue with a description of why there is this discrepancy and also whether you have a plan to fix it? Thanks!

**Comment by scorsett** [comment]
Hi @eycramer,

Thank you for bringing this to my attention. The discrepancy came from a slight difference between our model and the truth data for Saturday, September 5th. For future submissions, we will take a different approach to computing our one-week-ahead aggregate deaths that will remove the issue. We apologize for the inconsistency and look forward to fixing it.

**Comment by eycramer** [comment]
Thanks for addressing this! I'm closing the issue now.
