### ISSUE TITLE
consider other options for truth data

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#142]
USA facts: https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/
NYT: https://github.com/nytimes/covid-19-data
maybe others to consider as well

**Comment by jarad** [comment]
I think we should. I suggest a structure where in data-truth/ we have a subfolder for each of these different sources, e.g. data-truth/JHU/, data-truth/NYTimes/, and data-truth/USAfacts/.

**Comment by katiehouse3** [comment]
Is part of this issue to change the truth data on the visualization?

**Comment by jarad** [comment]
@katiehouse3 yes.

I have added these truth data to data-truth/

**Comment by nickreich** [comment]
if we want to use these data in different ways, let's add separate issues for those.
