### ISSUE TITLE
Visualization code quality (open to suggestions!)

### ISSUE THREAD

**Issue by hannanabdul55** [reichlab/covid19-forecast-hub#1457]
# Code quality improvements

If you find any code that is subpar (according to any standard), please post here! New issues will be added if needed.

## Original content:

Currently, the logic for initializing the layout of the visualization has a lot of quick _hacks_ put in place. This issue involves cleaning up the logic for the viz initialization as it is currently pretty messy. Here are some initial pointers:
- The first and major issue is to handle the `Show` toggle button properly (See image below)
![Screen Shot 2020-09-15 at 1 33 51 PM](https://user-images.githubusercontent.com/3615269/93244681-1a617a00-f758-11ea-8ea4-6cc2cec2e9ca.png). 
By default, when the viz is loaded, it is set to the `ensemble` option, which shows only the ensemble model. Internally, the code backing this could be cleaned up to handle this in a more elegant way. Specifically, you can start with [legend-drawer.js file](https://github.com/reichlab/covid19-forecast-hub/blob/master/visualization/vis-master/covid-d3-foresight/src/components/common/control-panel/legend-drawer.js).  
- The other is the code layout for handling model selection/deselection using events. these events are defined in [events.ts](https://github.com/reichlab/covid19-forecast-hub/blob/master/visualization/vis-master/covid-d3-foresight/src/events.ts) file.

**Comment by ydhuang28** [comment]
v2 of visualization should solve this. leaving it open, though, as it is a continuous task.
