### ISSUE TITLE
Visualization: Clicking a different state clears the selected forecasts

### ISSUE THREAD

**Issue by youyanggu** [reichlab/covid19-forecast-hub#1459]
Starting today, if I'm viewing multiple forecasts for one state and I click on another state, all of the selected models disappear and I have to re-select the models. This seems to happen in both incident and cumulative deaths view. This seems to only happen when multiple models are selected.

Let me know if you need more information to replicate. This is on Chrome.

**Comment by hannanabdul55** [comment]
Small issue. It is fixed. Will be live shortly! Thanks for reporting this!
