### ISSUE TITLE
validate representation of quantiles 

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#151]
we are having some issues with some forecasts where the quantiles are represented as long floats. See e.g. line 7 of this file:
https://raw.githubusercontent.com/reichlab/covid19-forecast-hub/master/data-processed/UT-Mobility/2020-04-27-UT-Mobility.csv

The only place I've seen this as a problem is in the UT models from @spencerwoody, although it may be elsewhere. 

This breaks the visualization of certain models. the 75th quantile isn't read in properly here so our 50% PI isn't shown properly:
![image](https://user-images.githubusercontent.com/1280767/80818073-9475d580-8ba0-11ea-884d-03e88e1cf175.png)

And it has also created ensemble headaches for @NutchaW.

So the question is how to manage this? Should we enforce that only certain quantiles are allowed? If so, should we only allow the 23 that we specify in README, or a wider set, like any quantile in the set `c(0.025, 0.0975, seq(0, 1, by=0.01))`? That would cover all bases (95% PI + any integer percentile). or is there a fancier CS way to enforce that the number of digits in a float in the `quantile` column isn't greater than 3?

**Comment by nickreich** [comment]
I'm also seeing these quantile issues in the MIT model files from @MichaelLLi , so this does appear to be a more general issue. (I haven't looked at other files).

**Comment by matthewcornell** [comment]
- The only check we do in [zolty](https://github.com/reichlab/covid19-forecast-hub/wiki/Validation-Checks) is: `checks entries in the quantile column must be numbers in [0, 1]`
- What is mathematically correct?
- How would it impact scoring (esp. in Zoltar)?
- How hard is it to require two-digit quantiles as you've requested in the project readme? Should we convert them ourselves?
- Zoltpy parses them using python, which will preserve whatever precision is passed in.

**Comment by jarad** [comment]
@matthewcornell FYI, we require a 3-digit quantile in the [Technical README](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md#quantile).

**Comment by jarad** [comment]
Round everything to 3 digits?

**Comment by jarad** [comment]
We decided to require submitted quantiles to be in the set of 23: `c(0.01, 0.025, seq(0.05, 0.95, by = 0.05), 0.975, 0.99)`

https://github.com/reichlab/covid19-forecast-hub/tree/master/data-processed#quantile

**Comment by spencerwoody** [comment]
The funny thing is that I actually used this syntax to define the
quantiles, but something broke when I used dplyr::group_by.  I will resolve
this issue in the new forecasts.

Thanks,
Spencer

**Comment by spencerwoody** [comment]
Hey guys, I'm really sorry for the headaches this has been causing. This
should hopefully be resolved with my latest PR. If not, I will sort it out
by today.

**Comment by matthewcornell** [comment]
I coded this up and ran it locally against the hub, and four files had invalid quantiles (with an example error for each):

- 2020-04-22-MIT_CovidAnalytics-DELPHI.csv
invalid quantile: '0.15000000000000002'. row=['2020-04-22', '42 day ahead cum death', '2020-06-03', '37', 'North Carolina', 'quantile', '0.15000000000000002', '230.74655870445343']
- 2020-04-27-MIT_CovidAnalytics-DELPHI.csv
invalid quantile: '0.15000000000000002'. row=['2020-04-27', '47 day ahead cum death', '2020-06-13', '54', 'West Virginia', 'quantile', '0.15000000000000002', '39.27133221012421']
- 2020-04-30-MIT_CovidAnalytics-DELPHI.csv
invalid quantile: '0.15000000000000002'. row=['2020-04-30', '25 day ahead cum death', '2020-05-25', '37', 'North Carolina', 'quantile', '0.15000000000000002', '841.9432970949123']
- 2020-04-20-UT-Mobility.csv
invalid quantile: '0.15000000000000002'. row=['2020-04-20', '1 day ahead inc death', '2020-04-21', '01', 'Alabama', 'quantile', '0.15000000000000002', '6.142857142857142']

**Comment by nickreich** [comment]
@MichaelLLi @spencerwoody could you update the offending files listed above before we add in this new validation?

**Comment by MichaelLLi** [comment]
Updated files and submitted pull request!
