### ISSUE TITLE
imperial incident week-ahead forecasts are not at right scale

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#154]
@sangeetabhatia03 the week-ahead incident death forecasts from Imperial do not appear to be at the right scale. I think they are maybe using the daily incident count for that Saturday, but they should be taking the total number of new deaths across a given week, from Sunday to Saturday. Can you re-do the calculations on the recent forecasts?

**Comment by mzorn-58** [comment]
@nickreich can we close this?

**Comment by nickreich** [comment]
I think at this point, these forecasts are not going to be updated, so we should just close this.
