### ISSUE TITLE
Covid-19 Makradakis Competition/Model Fit Tables and Hierarchical Rollup

### ISSUE THREAD

**Issue by pw08096** [reichlab/covid19-forecast-hub#156]
Since there are actuals and forecasts, why doesn't someone compute goodness of fit metrics like MAPE or RMSE by model by State with a rollup to National.  Rob Hyndman's work out of the University of Monash might be a starting point.  Makradakis would also be a  good starting point.  Hyndman's work is in CRAN-R.  It shouldn't be that hard.

**Comment by nickreich** [comment]
thanks for the suggestion! we are working on something similar, including some probabilistic scoring. Hopefully we will have some more detailed results within the week.
