### ISSUE TITLE
Update shiny app with ensemble checks

### ISSUE THREAD

**Issue by jarad** [reichlab/covid19-forecast-hub#162]
The [shiny app for visualizing](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/explore_processed_data.R) what forecasts we have needs to include checks for building the ensemble:

- [x] a column check for a median (have a median? - yes/no)
- [x] have all 1-4 wk ahead cum death? yes/no
- [x] have all 1-4 wk ahead inc death? yes/no
- [x] we need to see quantiles that most models overlap for that week, it can be shown in different ways: 1) find a common set of quantiles that most models overlap or 2) make a column with “matched” for the models that have that set of quantiles and “-” for those that don’t

**Comment by jarad** [comment]
@NutchaW Do we not have a specific set of quantiles we want to see? 

Also, what is the definition for "that week"? I'm thinking we need filter by forecast_date, but I'm not sure exactly what date should be used to filter. Of course, the app has the functionality for manual filter.

**Comment by NutchaW** [comment]
At this point the quantiles the ensemble include change every week depending on what the component models have (and the list of those component models has changed every week so far).  I don't know if we are moving toward having a more standardized process of running it or not. Maybe @nickreich can set a guideline regarding a minimum set of quantiles?

**Comment by jarad** [comment]
I will be filtering forecasts to ensure that the 

- `target_end_date` is 2020-05-09 and `target` is `1 wk ahead...` or 
- `target_end_date` is 2020-05-16 and `target` is `2 wk ahead...` or 
- `target_end_date` is 2020-05-23 and `target` is `3 wk ahead...` or 
- `target_end_date` is 2020-05-30 and `target` is `4 wk ahead...`

Does this sound reasonable?

**Comment by jarad** [comment]
@NutchaW time for you to take a look and provide feedback. Run the [shiny app](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/explore_processed_data.R) and go to the "Ensemble" tab. Let me know what you think.

I have assumed that teams have the same quantiles for every target and location. For example, if a team has a median for `cum death` but not for `inc death`, the app will report "Yes" for median. If we want to check by target or by location, we need to talk about exactly what checks we want to do.

**Comment by jarad** [comment]
We need a location check.

**Comment by nickreich** [comment]
can we close this issue now? seems like everything is resolved?
