### ISSUE TITLE
Include jurisdictions in interactive visualization

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#1659]
should add at least DC, PR, ideally all of the territories that are not states...

**Comment by ydhuang28** [comment]
DC is there. PR and others definitely should be added, though.

**Comment by nickreich** [comment]
@ydhuang28 Actually, I don't think DC is there. Just "Washington" state.

**Comment by ydhuang28** [comment]
Wait, are we talking about the map that you can hover your cursor over...?

**Comment by nickreich** [comment]
yes, and the drop-down menu.

**Comment by ydhuang28** [comment]
I do see a "District of Columbia", though. There is also a very minusculely visible DC on the map, I think.

**Comment by ydhuang28** [comment]
Ideally, though, we should add DC as separate, enlarged section (since it's nigh-impossible to click on that small area on the current map) and then other territories as well. I know that the code uses an external library to do show the interactive map so we might have to look into a different library that includes DC and the territories.

**Comment by nickreich** [comment]
you are right. my bad not seeing that. i was looking in the W's.

**Comment by mzorn-58** [comment]
Can we consider this issue completed?

**Comment by nickreich** [comment]
no. would still be nice to include somehow the territories and jurisdictions in the interactive visualization.

**Comment by ydhuang28** [comment]
This one is tricky. It's easy to add the territories in the drop-down menu, but I tried looking for a map that contains all of the contiguous 48 states, Alaska, Hawaii, Puerto Rico, Guam, Virgin Islands, Northern Mariana Islands, and American Samoa, but it seems that none actually exist. There is [one](https://bl.ocks.org/rveciana/5040be82aea528b6f785464f8816690f) using on congressional district boundaries but there might not be one that only contains the state boundaries. Just making a note here.

**Comment by nickreich** [comment]
Hmm. well then let's just add them to the drop-down menu. does that pose challenges? like, what happens if I want to move to the US level after having selected Guam? I would either use the drop-down menu or I could click on a state to select it and then click on the same state again to deselect.

**Comment by ydhuang28** [comment]
Yep, that's exactly how I'm doing it on my local development build. If you select one of the territories nothing will be highlighted on the map but the numbers over on the chart are correct, and only models that contain predictions for said territory are able to be selected.
