### ISSUE TITLE
Discrepancy between incidence and cumulative death forecasts for epiforecasts-ensemble1

### ISSUE THREAD

**Issue by eycramer** [reichlab/covid19-forecast-hub#1660]
Hi @kathsherratt,

We are filing this issue because we noticed that your one-week ahead forecasts of incident and cumulative deaths didn't agree with each other this week. We would expect the one-week ahead predictive median for cumulative deaths to be approximately equal to the last reported cumulative deaths plus the one-week ahead predictive median for incident deaths, but this was not the case for your forecast submitted this week. The reported cumulative deaths for the US as of Saturday October 3rd was 209,384, according to the data reported in the JHU CSSE repository at the end of day on Sunday October 4th. The median of your submitted one week ahead forecast for cumulative deaths was 212,250, which suggests a forecast of 2866 incident deaths. However, this is not in agreement with the median of the submitted one week ahead forecast for incident deaths, which was 4706.

We can imagine that this might happen for any of several reasons: for example, you may be using two different models to forecast incident and cumulative deaths, or you may be calculating cumulative deaths using a different reference data set or a different procedure for aggregating to the national level than we are (for reference, we describe our approach to calculating aggregated cumulative deaths based on the JHU CSSE data here. Regardless, we wanted to bring this discrepancy to your attention in case you were not aware of it.

Our goal is to make the ensemble forecasts of incident and cumulative deaths consistent with each other. This is only possible if the submitted forecasts of incident and cumulative deaths from each model are consistent with each other. Can you please respond to this issue with a description of why there is this discrepancy and also whether you have a plan to fix it? Thanks!

**Comment by kathsherratt** [comment]
Hi Estee,

Thanks so much for picking this up and for the useful description of the problem.

We've found and fixed the bug that caused this (PR [68](https://github.com/epiforecasts/covid-us-forecasts/pull/68) in our repo). This happened where we forecast based on incident counts, and then simply aggregate the cumulative forecast from that. Unfortunately there was a bug in this last step of formatting the cumulative forecast. This applied to only one type of model of several in the ensemble that we submit. We had not spotted this so thank you for flagging it! 

Frustratingly it looks like this may have affected the cumulative forecasts we have submitted for the last several months. (Meanwhile, the incident forecasts in the same files are the "correct" original forecast.) If it would be useful, we are happy to re-submit corrected versions of the cumulative forecasts. As the cumulative are generated directly from the incident forecasts, we would only be re-running the formatting step for the affected model, to create consistent submission files.  Please let me know if that's something that we can do.

We have also implemented an extra check on our side before submission to catch this if it happens again.

Thanks again for raising this.

Kath

cc @seabbs

**Comment by nickreich** [comment]
Hey @kathsherratt  - seems like your model put in incident death forecasts instead of cumulative death for this last week:
![image](https://user-images.githubusercontent.com/1280767/102719175-894ff100-42ba-11eb-8267-fc5050360f9e.png)

**Comment by eycramer** [comment]
Hi @kathsherratt,

Just bringing to your attention that the discrepancy this week between the 1 week ahead implied median (based on your cumulative death forecast) is -5,435 fewer deaths than the one week ahead calculated median from your incident death forecast.

The reported cumulative deaths for the US as of Saturday January 23rd was 417,439 according to the data reported in the JHU CSSE repository at the end of day on Sunday January 24th. The median of your submitted one week ahead forecast for cumulative deaths was 433,079, which suggests a forecast of 15,640 incident deaths. However, this is not in agreement with the median of the submitted one week ahead forecast for incident deaths, which was 21,075.

Best,
Estee
