### ISSUE TITLE
make x-axis end extend to June 2021

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#1669]

**Comment by Khoale1096** [comment]
Update: extend this feature to allow users to change the amount of time they are looking at similar to this example: https://bl.ocks.org/robyngit/89327a78e22d138cff19c6de7288c1cf

**Comment by nickreich** [comment]
@Khoale1096 and @mzorn-58  Maybe we should close this issue now? I've removed high priority issue for now.
