### ISSUE TITLE
Inconsistent presentation of DC in zoltar-truth.csv

### ISSUE THREAD

**Issue by JohnBurant** [reichlab/covid19-forecast-hub#1675]
Perhaps I'm missing something, but this seems like a bug to me:

(1) DC is present in zoltar-truth.csv as 2-digit FIPS 11 and 5-digit FIPS 11001.
(2) For 11, only 'cum death' shows as target
(3) For both 11 and 11001 both 'inc death' and 'cum death' show as targets
(4) For 11 and 11001 'cum death' targets match
(5) The value for 'inc death' target shown for 11001 is always TWICE the difference between subsequent timezero '1 wk ahead cum death' target values.

Example:

Cumulative deaths:
65143	2020-08-23	11	1 wk ahead cum death	605.0	state
65144	2020-08-23	11001	1 wk ahead cum death	605.0	other
66709	2020-08-30	11	1 wk ahead cum death	611.0	state
66710	2020-08-30	11001	1 wk ahead cum death	611.0	other
69319	2020-09-06	11	1 wk ahead cum death	616.0	state
69320	2020-09-06	11001	1 wk ahead cum death	616.0	other
70189	2020-09-13	11	1 wk ahead cum death	619.0	state
70190	2020-09-13	11001	1 wk ahead cum death	619.0	other
73669	2020-09-20	11	1 wk ahead cum death	624.0	state
73670	2020-09-20	11001	1 wk ahead cum death	624.0	other
140485	2020-09-27	11	1 wk ahead cum death	629.0	state
140486	2020-09-27	11001	1 wk ahead cum death	629.0	other

But incident deaths:
227379	2020-08-30	11001	1 wk ahead inc death	12.0	other
229944	2020-09-06	11001	1 wk ahead inc death	10.0	other
230799	2020-09-13	11001	1 wk ahead inc death	6.0	other
234219	2020-09-20	11001	1 wk ahead inc death	10.0	other
299883	2020-09-27	11001	1 wk ahead inc death	10.0	other

So actually the incremental deaths were 6, 5, 3, 5 not 12, 10, 6, 10. The former show up in the viz.

Ignore leftmost numbers, just my pd.DataFrame index.

**Comment by hannanabdul55** [comment]
Hi @JohnBurant , thanks for reporting this! The double truth data values for DC is fixed in #1700. You can run these checks on the new `zoltar-truth.csv` and confirm.

**Comment by hannanabdul55** [comment]
Closing it as it is fixed now.
