### ISSUE TITLE
create unit tests for truth data

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#1691]
Per suggestions from @elray1 ...
- [ ] Exactly the expected combinations of location, week, and target show up in the results.  i.e., all expected locations in combination with every possible week so far and target, and no unexpected locations, weeks, or targets
- [ ] For all timezeros within the same week span, truth values for all duplicated locations and targets are identical
- [ ] It's possible to correctly reconstruct cumulative values in the JHU csv file from cumulative values in the truth source.  i.e., can convert from cumulative numbers in the truth file back to the jhu csv values.
- [ ] It's possible to correctly reconstruct cumulative values in the JHU csv file from incident values in the truth source.  i.e., can convert from incident numbers in the truth file back to the jhu csv values.
- [ ] I'm not sure how to test that aggregation from county to state/national level is done correctly.  Maybe test agreement between python code output and covidData?  Then at least we'd know the two implementations agreed (or not).

**Comment by ydhuang28** [comment]
Perhaps we should handcraft a small CSV that includes all the above scenarios to test?

**Comment by Khoale1096** [comment]
- [ ] Add unit test framework for truth data similar to : https://github.com/reichlab/covid19-forecast-hub/blob/d3a9b4b447cb2fa557e7f77baa753cceafc63500/code/test/test_upload_covid_all_forecasts.py 
- [ ] Refactor truth code to make it more modular - Move more common functionality to truth_utils. 
- [ ] Create sample truth data csv file similar to JHU CSSE data to be used for the unit tests. 
- [ ] Create unit tests for the method that creates the data frame to check for expected combinations of headers, all expected locations in combination with every possible week so far and target, and unexpected location/week/target
- [ ] TO BE ADDED MORE

**Comment by elray1** [comment]
I created issues https://github.com/reichlab/covidHubUtils/issues/45 and https://github.com/reichlab/covidHubUtils/issues/46, so am closing this one.
