### ISSUE TITLE
Discrepancy between incidence and cumulative death forecasts for BPagano-RtDriven

### ISSUE THREAD

**Issue by eycramer** [reichlab/covid19-forecast-hub#1725]
Hi @rjpagano ,

We are filing this issue because we noticed that your one-week ahead forecasts of incident and cumulative deaths didn't agree with each other this week. We would expect the one-week ahead predictive median for cumulative deaths to be approximately equal to the last reported cumulative deaths plus the one-week ahead predictive median for incident deaths, but this was not the case for your forecast submitted this week. The reported cumulative deaths for the US as of Saturday October 10th was 214,370 according to the data reported in the JHU CSSE repository at the end of day on Sunday October 11th. The median of your submitted one week ahead forecast for cumulative deaths was 218,396, which suggests a forecast of 4026 incident deaths. However, this is not in agreement with the median of the submitted one week ahead forecast for incident deaths, which was 5347.

We can imagine that this might happen for any of several reasons: for example, you may be using two different models to forecast incident and cumulative deaths, or you may be calculating cumulative deaths using a different reference data set or a different procedure for aggregating to the national level than we are (for reference, we describe our approach to calculating aggregated cumulative deaths based on the JHU CSSE data here. Regardless, we wanted to bring this discrepancy to your attention in case you were not aware of it.

Our goal is to make the ensemble forecasts of incident and cumulative deaths consistent with each other. This is only possible if the submitted forecasts of incident and cumulative deaths from each model are consistent with each other. Can you please respond to this issue with a description of why there is this discrepancy and also whether you have a plan to fix it? Thanks!

**Comment by eycramer** [comment]
Hi @rjpagano, 

Just bringing to your attention that the discrepancy this week between the 1 week ahead implied median (based on your cumulative death forecast) is 14,544 fewer deaths than the one week ahead calculated median from your incident death forecast.

The reported cumulative deaths for the US as of Saturday January 23rd was 417,439 according to the data reported in the JHU CSSE repository at the end of day on Sunday January 24th. The median of your submitted one week ahead forecast for cumulative deaths was 422,822, which suggests a forecast of 5383 incident deaths. However, this is not in agreement with the median of the submitted one week ahead forecast for incident deaths, which was 19,928. 

If this was caused by a bug or some other issue, you can submit a new PR with your forecast file with a description of why you are making the change. 

Thanks!
Estee

**Comment by rjpagano** [comment]
Hello Estee,

Thank you for pointing out this issue to me. I have corrected my forecast as described in the screen capture below.
Can you tell me why the "Create pull request" tab is "greyed out" in this github request?

Thank you,

Bob
