### ISSUE TITLE
Missing FIPS 11001 in truth-Cumulative Cases.csv

### ISSUE THREAD

**Issue by FrostXTJ** [reichlab/covid19-forecast-hub#1919]
I think the truth-Cumulative Cases.csv fetches data from JHU's dataset, but FIPS 11001 (District of Columbia) is missing in your file. Can anyone fix it?

**Comment by nickreich** [comment]
We think that FIPS 11 and FIPS 11001 refer to the same locations, so you can find the data for 11001 under FIPS==11. We should document this decision more clearly on the Truth data wiki page: https://github.com/reichlab/covid19-forecast-hub/wiki/Truth-Data

**Comment by ydhuang28** [comment]
Wiki has be updated. Closing this issue now.
