### ISSUE TITLE
Upload to zoltar action fails in subsequent runs if a job timed out during a previous run

### ISSUE THREAD

**Issue by ydhuang28** [reichlab/covid19-forecast-hub#1984]
Per @Khoale1096, this is because the hashes of the other uploaded forecasts are not recorded in [`code/zoltar_scripts/validated_file_db.json`](https://github.com/reichlab/covid19-forecast-hub/blob/master/code/zoltar_scripts/validated_file_db.json).

Specifically, what happens is: (@Khoale1096 do feel free to correct/append as needed!)
1. A job for upload forecast A times out. Other jobs for uploading forecasts B, C, D, ... may succeed.
2. Since the script quits when an upload job fails, the subsequent step of adding the hash of the succeeded forecasts B, C, D... is not executed, and the hashes for B, C, D... are not recorded in the hash table.
3. The next time the Action is run, the script will try to upload B, C, D, ... since the script uses the hash table to determine whether a forecast has or has not been uploaded. Therefore within the same Action, other succeeded forecasts E, F, G, ... may have their hashes left out as well.
4. This sequence cascades.

The immediate fix is to remove the forecasts that have been uploaded to Zoltar but do not have a hash in [`code/zoltar_scripts/validated_file_db.json`](https://github.com/reichlab/covid19-forecast-hub/blob/master/code/zoltar_scripts/validated_file_db.json), and then rerun the Action.

Long-term, the script should be fixed so that an upload job succeeding guarantees the hashes of the uploaded forecast is recorded.

**Comment by ydhuang28** [comment]
I'm working on the immediate fix right now.

**Comment by Khoale1096** [comment]
@ydhuang28 Correction for the immediate fix: I would recommend examining the `code/zoltar_scripts/validated_file_db.json` versus Zoltar. If there are forecasts uploaded to Zoltar recently but is not added to this json, then proceed to remove those forecasts *from Zoltar*, and then re-trigger the action. Therefore all new forecasts can be re-uploaded fresh and synchronize with the json file.
