### ISSUE TITLE
Look at the existing tests in covidData and see if some items have been identified that are not covered in current covidData tests; create issues for missing tests; write the tests

### ISSUE THREAD

**Issue by mzorn-58** [reichlab/covid19-forecast-hub#1991]

**Comment by mzorn-58** [comment]
@elray1 Devteam thinks this belongs in covidData.  Does that seem reasonable to you?

**Comment by elray1** [comment]
@mzorn-58  Yes this could go into covidData

**Comment by elray1** [comment]
I created issues https://github.com/reichlab/covidHubUtils/issues/45 and https://github.com/reichlab/covidHubUtils/issues/46, so am closing this one.
