### ISSUE TITLE
Will new target codes be available?

### ISSUE THREAD

**Issue by RobertWalraven** [reichlab/covid19-forecast-hub#2047]
We were asked today to provide 30-day forecasts and forecasts on the 52 new HealthData.gov fields.   In order to use the existing processing procedures I'm assuming that simply by having new target codes for these new quantities we will be able to add the forecasts for this new data to our existing submissions.   Is that correct?  If not, what is the proposed method for reporting this data.

Is the CDC looking for forecasts on all 52 of the new hospitalization fields or are only some of them of interest?  Data for 53 new fields would make make the forecast files quite large.

Also will there be a shorter set of quantiles to be used, like with the case data?

**Comment by nickreich** [comment]
We are actively learning about and exploring these data, but for now, our recommendations are posted here: https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md#hospitalizations
