### ISSUE TITLE
NYTimes truth data issue breaks automatic truth upload

### ISSUE THREAD

**Issue by Khoale1096** [reichlab/covid19-forecast-hub#2127]
Weekly truth upload for this week [failed](https://github.com/reichlab/covid19-forecast-hub/runs/1470286830?check_suite_focus=true). The reason is because of NYTimes's changes in format for their us-counties.csv, covering Puerto Rico, documented in this nytimes/covid-19-data#507.

Actions:

- [ ] As JHU, USAFacts also use the same github action to process + upload truth, this issue with NYTimes prevents these other 2 truth sources to be process and uploaded. A quick workaround is to add another 2 separate Github actions that own the processing and uploading truth for JHU and USAFacts respectively, avoiding the issue. Maybe there's a better way to do this though @nickreich @hannanabdul55 @ydhuang28?
- [ ] The changes made in nytimes/covid-19-data#507 seems to be permanent from now on for NYTimes, we need to adjust [nytimes.py](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-truth/nytimes/nytimes.py) to accommodate this change (and later on in `covidHubUtils` as all the truth codes will be migrated there)

**Comment by nickreich** [comment]
separate actions seems like a reasonable robustification of these scripts to me. maybe slightly lower priority than just fixing the nytimes.py script, though? could be split into a secondary issue.
