### ISSUE TITLE
Discrepancy between incidence and cumulative death forecasts for Karlen-pypm

### ISSUE THREAD

**Issue by eycramer** [reichlab/covid19-forecast-hub#2174]
Hi @deankarlen,

We are filing this issue because we noticed that your one-week ahead forecasts of incident and cumulative deaths didn't agree with each other this week. We would expect the one-week ahead predictive median for cumulative deaths to be approximately equal to the last reported cumulative deaths plus the one-week ahead predictive median for incident deaths, but this was not the case for your forecast submitted this week. The reported cumulative deaths for the US as of Saturday November 28th was 266,047
according to the data reported in the JHU CSSE repository at the end of day on Sunday November 29th. 

The median of your submitted one week ahead forecast for cumulative deaths was 411,796.5, which suggests a forecast of 145,749.5 incident deaths. However, this is not in agreement with the median of the submitted one week ahead forecast for incident deaths, which was 12,796. 

We can imagine that this might happen for any of several reasons and we wanted to bring this discrepancy to your attention in case you were not aware of it.

Our goal is to make the ensemble forecasts of incident and cumulative deaths consistent with each other. This is only possible if the submitted forecasts of incident and cumulative deaths from each model are consistent with each other. Can you please respond to this issue with a description of why there is this discrepancy and also whether you have a plan to fix it? Thanks!

**Comment by deankarlen** [comment]
Hi Estee,

  Thanks for notifying me of this issue. On the weekend, I modified the code to run many more iterations to produce smoother quantiles. Unfortunately, with the deadlines, I did not get a chance to check all results before submitting.

  Thanks to your report, I discovered the mistake in the code (one line) that caused this unusual behaviour. I corrected that and produced a new forecast file that I just uploaded. The only changes are in the quantiles for the cumulative deaths for US as a whole. The new file now has consistent medians.

Regards,
Dean
