### ISSUE TITLE
Move licenses to data-processed/

### ISSUE THREAD

**Issue by jarad** [reichlab/covid19-forecast-hub#228]
I think we should move licenses to data-processed/ since some teams don't even have a folder in data-raw/ and some teams, e.g. [MIT](https://github.com/reichlab/covid19-forecast-hub/tree/master/data-raw/MIT), only have a license file in data-raw/. Moving everything to data-processed/ will consolidate files to data-processed/.

I'm willing to move the files and update the README to indicate the new location, but I'm wondering if there is any input on this.

**Comment by nickreich** [comment]
i think this is a great idea.
