### ISSUE TITLE
document the checks that should be in place for metadata

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#230]

**Comment by nickreich** [comment]
- team name should be unique
- model name should be unique
- needs to be readable metadata file (no tabs)
- no special characters without being wrapped in double quotes
- special formatting for long-form answers
- length of model name should be less than 15 characters and not include hyphens
- length of team name should be less than 15 characters and not include hyphens
- all fields needed for visualization should be present
- list of required vs optional fields

**Comment by jarad** [comment]
I think it is team_abbr and model_abbr that need to be less than 15 characters.
