### ISSUE TITLE
Discrepancy between incidence and cumulative death forecasts for COVIDAnalytics-DELPHI

### ISSUE THREAD

**Issue by eycramer** [reichlab/covid19-forecast-hub#2325]
Hi @MichaelLLi ,

We are filing this issue because we noticed that your one-week ahead forecasts of incident and cumulative deaths didn't agree with each other this week. We would expect the one-week ahead predictive median for cumulative deaths to be approximately equal to the last reported cumulative deaths plus the one-week ahead predictive median for incident deaths, but this was not the case for your forecast submitted this week. The reported cumulative deaths for the US as of Saturday December 12th was 297,818 according to the data reported in the JHU CSSE repository at the end of day on Sunday December 13th. The median of your submitted one week ahead forecast for cumulative deaths was 323,044, which suggests a forecast of 25,226 incident deaths. However, this is not in agreement with the median of the submitted one week ahead forecast for incident deaths, which was 14,324. 

We can imagine that this might happen for any of several reasons and we wanted to bring this discrepancy to your attention in case you were not aware of it.

Can you please respond to this issue with a description of why there is this discrepancy and also whether you have a plan to fix it? Thanks!

**Comment by MichaelLLi** [comment]
Hi @eycramer , I'm so sorry! I somehow didn't see the issue existed until you closed it - I presume our forecasts in the recent weeks did not have this issue? Thanks!

**Comment by eycramer** [comment]
Hi @MichaelLLi 

Not a problem! 

There have been slight discrepancies in recent weeks (about 1,000 deaths). 

This was an old issue but we regenerate the discrepancies each week, so I can let you know if we still see the same trend in coming weeks. 

-Estee

**Comment by MichaelLLi** [comment]
Got it! I will check this with my team on our end. Thanks for raising this!
