### ISSUE TITLE
add "N wk ahead cum/inc case"

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#233]
mandatory
- add targets to validation
- add targets to Zoltar

optional
- add targets to truth
- add targets to visualization

**Comment by jarad** [comment]
[NYTimes](https://github.com/reichlab/covid19-forecast-hub/tree/master/data-truth/nytimes) and [USAFacts](https://github.com/reichlab/covid19-forecast-hub/tree/master/data-truth/usafacts) data already have these targets.

**Comment by katiehouse3** [comment]
- [ ] validation
- [ ] Zoltar
- [ ] truth
- [ ] visualization

@nickreich Should we close or is it still good to look into adding these targets to truth / visualization?

**Comment by nickreich** [comment]
I think there is a longer term question about whether we should be including this as a target. this is not an immediate need or priority for the group, so I am closing the issue.
