### ISSUE TITLE
missing `scores-latest.json`

### ISSUE THREAD

**Issue by sbfnk** [reichlab/covid19-forecast-hub#2334]
Trying a local build of the visualisations yields an error because `../assets/data/scores-latest.json` is referenced here:

https://github.com/reichlab/covid19-forecast-hub/blob/30adaf2fd91af099cee0454388bb073675fba829/visualization/vis-master/src/store/data.js#L6

but missing here:

https://github.com/reichlab/covid19-forecast-hub/tree/master/visualization/vis-master/src/assets/data

**Comment by ydhuang28** [comment]
Hi! If you have a local clone of the repository, please follow [these steps](https://github.com/reichlab/covid19-forecast-hub/wiki/Building-the-Visualization-Locally) to generate a local build. The `scores-latest.json` file will be generated in those steps.

**Comment by sbfnk** [comment]
That's what I did but it didn't get generated. If you could point me to where the file gets created I'll try to have another look at why it didn't happen.
