### ISSUE TITLE
mmwr-week module for visualization

### ISSUE THREAD

**Issue by tkcy** [reichlab/covid19-forecast-hub#245]
Hi! I'm trying to follow the instructions on building your visualization tool locally, and am getting the following error in ./0-init-vis.sh :

```
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module 'mmwr-week'
```

I already installed the dependancies listed on the instruction page.  Do you know how/where I get this module?

Thanks!

**Comment by nickreich** [comment]
can you give more context about your system? what OS? what version of python, node, etc?

**Comment by jarad** [comment]
We are closing this since we have not received a response, but if it is still an issue, please feel free to re-open.
