### ISSUE TITLE
Rescale the color scale after using rates instead of absolute

### ISSUE THREAD

**Issue by ApurvShah007** [reichlab/covid19-forecast-hub#2462]
After the rates have been implemented, is there a need to rescale the color scale on the map to show the subsequent change in numbers? As the entire map is naturally lighter.

**Comment by ApurvShah007** [comment]
The upper bound is manually hardcoded to some value for each variable, this is the reason why we cant just rescale it

**Comment by ydhuang28** [comment]
Planned incorporation into v2.
