### ISSUE TITLE
Validation of forecast files submit date less than (issue date + 1d)

### ISSUE THREAD

**Issue by mzorn-58** [reichlab/covid19-forecast-hub#2589]
Add automation check for forecasts uploaded > 24 hours after appropriate Monday deadline.  

See https://reichlab.slack.com/archives/C011SKXLBA8/p1610122399412600

# Description
- Add a validation check to ensure that the date at which the forecast is submitted has a date within 24 hours of the date on the forecast file. 
- The date to check would be the date at which the validation was run. 
- Send a comment/warning about the date of the forecast. 
- The date to be checked would be in EST.

**Comment by ydhuang28** [comment]
@hannanabdul55 is monitoring the migration process. Will close when old validation is removed.

**Comment by hannanabdul55** [comment]
This is done. Closing it.
