### ISSUE TITLE
Improve validations check speed

### ISSUE THREAD

**Issue by hannanabdul55** [reichlab/covid19-forecast-hub#2594]
## Description
- Reduce the validation check speed by skipping the download of all the files and just downloading the files that have been changed in the PR and checking only those files. 
- Use the Github API to fetch the files and validate them on Github.

**Comment by ydhuang28** [comment]
Also part of new validation process. Will close when old validation workflows are removed.

**Comment by hannanabdul55** [comment]
Done in the covid19-forecast-hub-validations repository.
