### ISSUE TITLE
create central list of forecast submissions that have been deleted and reasons for deletion

### ISSUE THREAD

**Issue by elray1** [reichlab/covid19-forecast-hub#2661]
Steps to do this:

- [ ] write a script to parse output from something like `git log --diff-filter=D --summary` (or similar) into a spreadsheet with columns like file name, commit/pr date, commit/pr link
- [ ] as a group, go through and annotate these with reasons for deletion or a statement that this deletion may have been unintentional

**Comment by Khoale1096** [comment]
@elray1 I ran the command ` git log --diff-filter=D --summary -- "data-processed" > code/misc/file_delete.txt` to get the log output and made a short script that parse these outputs into a csv file 4 columns `file_name, commit_date, commit_link, commit_message`. The output csv can be seen in this [PR](https://github.com/reichlab/covid19-forecast-hub/pull/2732/files). Please let me know if there are other info you want me to query/ or if these are the correct info you are looking for.
