### ISSUE TITLE
Switch truth update to use covidHubUtils + covidData on the VM

### ISSUE THREAD

**Issue by Khoale1096** [reichlab/covid19-forecast-hub#2665]
## Description
We would like to move from using the python scripts under `data-truth/` directory to using covidHubUtils/covidData to update the truth for GitHub and Zoltar, mainly because:

1. All codes for truth aggregation and the creation of corresponding csv files are centralized and unit-tested in covidHubUtils/covidData, so we want to make use of that, instead of the non unit-tested python scripts as of currently
2. With the Virtual Machine being ready, we now have enough capacity to frequently utilize covidData.

## Steps of Actions
- [x] Install covidData on the VM.
- [x] Install covidHubUtils on the VM.
- [x] Creates a cron job that daily update covidData & covidHubUitls to have the latest features
- [x] Automate hospitalization truth as part of the move
- [x] Creates another cron job that weekly update the truth csv files using a script similar to [this](https://github.com/reichlab/covid19-forecast-hub/blob/master/travis/update_truth_weekly.sh), making use of those 2 packages and push to GitHub.
- [x] Add a GitHub action that can trigger this action on the VM and retire the current github action that perform weekly truth update
- [x] Update truth wiki to reflect this change

**Comment by ydhuang28** [comment]
Is there anything you need from me for configuration, etc.? FYI all code is located at `/code` on the VM.

**Comment by Khoale1096** [comment]
Github Action reaches capacity limit. Revert back to plan to use VM
