### ISSUE TITLE
Update list of teams in ReadMe

### ISSUE THREAD

**Issue by jbracher** [reichlab/covid19-forecast-hub#271]

**Comment by jarad** [comment]
List of teams in data-processed/

- [ ] Aquaun
- [ ] CU
- [ ] CovidActNow
- [ ] ERDC
- [ ] GT
- [ ] Geneva
- [ ] IHME
- [ ] Imperial
- [ ] IowaStateLW
- [ ] JHU
- [ ] LANL
- [ ] MIT
- [ ] MOBS
- [ ] NotreDame
- [ ] PSI
- [ ] Quantori
- [ ] UA
- [ ] UCLA
- [ ] UChicago
- [ ] UMASS
- [ ] UT
- [ ] YYG

As teams are added to README, they will be checked off.

**Comment by jarad** [comment]
I believe all the teams are in the README.
