### ISSUE TITLE
update validations to not allow columns that are not list of required OR optional names

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#272]

**Comment by matthewcornell** [comment]
@katiehouse3 @nickreich Do you have a little detail about this? An example would be great.

**Comment by jarad** [comment]
Primarily teams have an unnamed column that are row numbers. When running shiny app, these are the warnings you get 

    Warning messages:
    1: ./Auquan-SEIR/2020-05-11-Auquan-SEIR.csv: Missing column names filled in: 'X1' [1]
    2: ./Auquan-SEIR/2020-05-18-Auquan-SEIR.csv: Missing column names filled in: 'X1' [1]
    3: ./UChicago-CovidIL_10_increase/2020-05-18-UChicago-CovidIL_10_increase.csv: Missing column names filled in: 'X1' [1]
    4: ./UChicago-CovidIL_100/2020-05-05-UChicago-CovidIL_100.csv: Missing column names filled in: 'X1' [1]
    5: ./UChicago-CovidIL_100/2020-05-11-UChicago-CovidIL_100.csv: Missing column names filled in: 'X1' [1]
    6: ./UChicago-CovidIL_100/2020-05-18-UChicago-CovidIL_100.csv: Missing column names filled in: 'X1' [1]
    7: ./UChicago-CovidIL_30_increase/2020-05-18-UChicago-CovidIL_30_increase.csv: Missing column names filled in: 'X1' [1]
    8: ./UChicago-CovidIL_40/2020-05-05-UChicago-CovidIL_40.csv: Missing column names filled in: 'X1' [1]
    9: ./UChicago-CovidIL_40/2020-05-11-UChicago-CovidIL_40.csv: Missing column names filled in: 'X1' [1]
    10: ./UChicago-CovidIL_60/2020-05-05-UChicago-CovidIL_60.csv: Missing column names filled in: 'X1' [1]
    11: ./UChicago-CovidIL_60/2020-05-11-UChicago-CovidIL_60.csv: Missing column names filled in: 'X1' [1]
    12: ./UChicago-CovidIL_80/2020-05-05-UChicago-CovidIL_80.csv: Missing column names filled in: 'X1' [1]
    13: ./UChicago-CovidIL_80/2020-05-11-UChicago-CovidIL_80.csv: Missing column names filled in: 'X1' [1]

**Comment by matthewcornell** [comment]
OK, given @jarad 's comment, this issue's title is inaccurate. Recall that a while back we added the feature to allow extra non-required columns without error. So is this issue asking to check for blank column names in the header?

**Comment by nickreich** [comment]
since we removed the location_name column i think this is not relevant anymore.
