### ISSUE TITLE
add method for tracking which models to include in ensemble

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#273]
one option: add `include_in_ensemble` field to metadata file. If we did this, We would need to verify that for teams with multiple models, only one of these is "true" and also allow teams to modify their choice week to week

Another option: have a single csv file that we keep somewhere that has a manually compiled list of all eligible models (including just one from each team.

**Comment by katiehouse3** [comment]
Is this also looped into #351 ?

**Comment by nickreich** [comment]
I think this issue is included in other issues regarding updated metadata integration into zoltar.
