### ISSUE TITLE
update forecast dates for IHME models

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#279]
in most cases the forecast_date associated with the IHME models is currently the folder name but this does not correspond with the "model release date". See below figure for appropriate mappings. 
![image](https://user-images.githubusercontent.com/1280767/81695018-0ddab700-9430-11ea-9ec7-e57327cca834.png)
Also, 2020-05-08 should be changed to 2020-05-10.

**Comment by mzorn-58** [comment]
@nickreich can this be closed?

**Comment by nickreich** [comment]
I guess at this point, these one-day discrepancies in forecast_date and/or timezeroes are kind of negligible in the big picture. closing for now.
