### ISSUE TITLE
Discrepancy between incidence and cumulative death forecasts for SteveMcConnell-CovidComplete

### ISSUE THREAD

**Issue by eycramer** [reichlab/covid19-forecast-hub#2800]
Hi @stevemcconnell, 

I'm are filing this issue because we noticed that your one-week ahead forecasts of incident and cumulative deaths didn't agree with each other this week. We would expect the one-week ahead predictive median for cumulative deaths to be approximately equal to the last reported cumulative deaths plus the one-week ahead predictive median for incident deaths, but this was not the case for your forecast submitted this week. The reported cumulative deaths for the US as of Saturday January 30th was 439,530 according to the data reported in the JHU CSSE repository at the end of day on Sunday January 31st. The median of your submitted one week ahead forecast for cumulative deaths was 501,774, which suggests a forecast of 62,244 incident deaths. However, this is not in agreement with the median of the submitted one week ahead forecast for incident deaths, which was 18,022.

We can imagine that this might happen for any of several reasons and we wanted to bring this discrepancy to your attention in case you were not aware of it.

Can you please respond to this issue with a description of why there is this discrepancy and whether you have a plan to fix it? Thanks!

**Comment by stevemcconnell** [comment]
Hi @eycramer, That cumulative number is definitely an error. I changed how I was importing the JHU data last week, and it looks like I added the numeric value of Saturday, 1/30/2021 into the cumulative forecasts. All of the cumulative forecasts I submitted yesterday will be high by 44,227. 

I've created a pull request to update the cumulative forecasts. Thanks for bringing this to my attention!
