### ISSUE TITLE
Pull request not running checks automatically for us

### ISSUE THREAD

**Issue by erdc-cv19** [reichlab/covid19-forecast-hub#294]
The checks on our pull request do not seem to be running automatically.  How long does it take for the checks to run?  We passed the checks locally with the python scripts and viewed everything within the R Shiny notebook.

Pull request: #293

**Comment by nickreich** [comment]
Thanks, we are looking into this! It happend with another PR yesterday, and we have not isolated the bug yet.

**Comment by Khoale1096** [comment]
The GitHub system was down for 20 minutes according to [here](https://www.githubstatus.com/). It's resolved by the GitHub team and the PR is being run through checks right now. Sorry for the inconvenience!
