### ISSUE TITLE
implement two checks for updated files in PRs

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#3228]
For PR submissions that update existing forecast files, currently these are flagged as "forecast-updated". In addition, we would like to implement the following two checks, to start to inch us closer to Zoltar v4.0 compliance:

 - [ ] the updated file should contain predictions for all locations/targets/types that are in the existing file. E.g. if a file made a point prediction and a quantile prediction for "US" location, "1 wk ahead inc death" then the update should also have quantile and point predictions. If it doesn't let's for now add a "forecast-retraction" flag to the PR. Later, once Zoltar v4.0 is live and we have specific instructions for "explicit retractions", we will make this condition a "failing" condition.
 - [ ] the updated file cannot contain 100% duplicated rows from the existing file. The case we are thinking about is if rows are reordered but contain the same information as the existing file.

**Comment by hannanabdul55** [comment]
I have a sample PR that implements the validation for point 1 here in this PR - https://github.com/hannanabdul55/covid19-forecast-hub/pull/5
