### ISSUE TITLE
data submission format issue for IUPUI-HkPrMobiDyR

### ISSUE THREAD

**Issue by chiangwe** [reichlab/covid19-forecast-hub#3240]
Hi, I would like to remove my submission of **"./IUPUI-HkPrMobiDyR/2021-02-22-IUPUI-HkPrMobiDyR.csv"**
There was a misunderstanding of targets for "2-4 weeks ahead." We used cumulative forecasts instead of cases within the given window. Would you help me to remove this entry? Even better, if I can resubmit.

**Comment by nickreich** [comment]
Please resubmit the file and explain the update in the PR. thanks!
