### ISSUE TITLE
No Space Left on Device for GitHub Action

### ISSUE THREAD

**Issue by Khoale1096** [reichlab/covid19-forecast-hub#3244]
Zoltar Upload has been failing since Friday with the error indicating we're at limit for device storage in GitHub Action

https://github.com/reichlab/covid19-forecast-hub/runs/2142306517?check_suite_focus=true

- [x] Temporary Fix: Remove the steps: checking actions/setup-node@v1 and npm install
- [x] Temporary Fix: remove preinstalled software from GitHub [PR](https://github.com/reichlab/covid19-forecast-hub/pull/3253)
- [ ] Long-term: use of this GH action https://github.com/easimon/maximize-build-space, which can save up to 40 GBs

**Comment by hannanabdul55** [comment]
I think we should probably be moving this build to the VM. It would be much faster, as we won't have to do an entire git clone every time.
