### ISSUE TITLE
When is the Interactive plot updated?

### ISSUE THREAD

**Issue by erdc-cv19** [reichlab/covid19-forecast-hub#327]
We assumed that we'd see our projections against everyone else's based on the detailed instructions...We realize you all had a massive increase in submissions today.  Obviously we have people breathing down our necks (:-D) to see our plots against the other models.  Any info is appreciated.

Cheers and thank you for putting the effort  in to make such an amazing ensemble of models.

**Comment by nickreich** [comment]
It is not (yet) a fully automated process to build the ensemble or the visualization. We typically release an updated visualization and ensemble model by noon ET on Tuesday.

**Comment by nickreich** [comment]
y
