### ISSUE TITLE
baseline misalignment?

### ISSUE THREAD

**Issue by tkcy** [reichlab/covid19-forecast-hub#337]
Hi again!
Can you clarify what is meant by baseline misalignment in the ensemble criteria?  I see this is listed as the issue with CU-select in 2020-05-19-model-eligibility.csv, but I'm not sure which of the requirements this refers to.  Thanks!

**Comment by nickreich** [comment]
@tkcy this was a visual inspection check that showed misalignment with observed data in a lot of locations.  

@elray1 could you point out a few of the locations where we saw this specifically?

**Comment by elray1** [comment]
The most prominent examples were Alaska, Rhode Island, and North Dakota.  There were several other locations where based on visual inspection it appeared that there was some disagreement between the 1 week ahead predictions and the observed value (based on JHU data) for the most recent week, though those other examples were less serious than the three listed above.

**Comment by tkcy** [comment]
Ok thanks.  Rhode Island was a bug related to our treatment of statewide unallocated data that was eventually assigned to a county.  But the rest appear to be due to the difference in the data source - we use USA Facts.  Are you now requiring JHU data?  Making the switch has been on our to-do list, but we haven't prioritized it.

**Comment by nickreich** [comment]
@tkcy We don't "require" teams to use any particular data source, but our current plan is to validate forecasts using the JHU truth data and to build ensembles to predict based on these counts. This has been our position since the beginning.

**Comment by tkcy** [comment]
@nickreich  Ok thanks - we'll try to make the switch in the next week or two.
