### ISSUE TITLE
add commented out fields to metadata checks

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#342]
- team_url: check valid URL
- license: select from a list, including "other"
- include_in_ensemble_and_visualization: boolean

**Comment by jarad** [comment]
A [list of licenses](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) we should allow. Also "other" and "none", IMO.

**Comment by katiehouse3** [comment]
@jarad I like that list. I'll require `license` to be one of these abbreviations or "Other"

**Comment by katiehouse3** [comment]
These are written and will be included in the metadata check merge
