### ISSUE TITLE
Zoltar Upload Failed due to errors while installing dependency

### ISSUE THREAD

**Issue by Khoale1096** [reichlab/covid19-forecast-hub#3454]
Recent [builds](https://github.com/reichlab/covid19-forecast-hub/runs/2287171684?check_suite_focus=true) are failing while installing pandas. Assigning @hannanabdul55 since it seems to be related to the pandas 1.1.0 version

**Comment by hannanabdul55** [comment]
Reverted by removed the version specification. Closing this until I figure out an alternate.
