### ISSUE TITLE
document process for implementing new checks

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#350]
@Khoale1096 suggests we have a procedure where any new validation/test is submitted as a PR from a branch with ALL forecast files present in the branch but also all files removed from the validated_files.csv, to ensure that all files pass before the new validation is merged.

The issue here is just to document this process so it's clear. And then it's just a procedure that we need to follow each time we make such an update.

**Comment by matthewcornell** [comment]
I don't think I know enough about the whole PR process to comment, unless I'm misunderstanding this issue.

**Comment by nickreich** [comment]
Closed by the updates to the wiki about GitHub actions.
