### ISSUE TITLE
create single file with list of candidate models to include in visualization

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#351]
should be a file, ideally created from metadata of all models in the repo, with columns for
 - team_abbr
 - model_abbr
 - team_model `[team_abbr]-[model_abbr]`
 - maybe zoltar model number?

we need to decide what to call the new field in metadata before we do this.

**Comment by jarad** [comment]
I think #349 needs to happen first

**Comment by nickreich** [comment]
We should now rely on the `model_designation` field in metadata to determine whether a model is plotted or not.

**Comment by hannanabdul55** [comment]
@nickreich What are the model to be considered? Only `primary`?

**Comment by nickreich** [comment]
@hannanabdul55 is this still relevant?

**Comment by hannanabdul55** [comment]
Depends on if we need it now. Should be straightforward to add if we need it 👍

**Comment by nickreich** [comment]
@ydhuang28 can you look at how we decide whether models are added to the visualization or not and adjudicate whether we still need this issue open or not?

**Comment by ydhuang28** [comment]
Will do!

**Comment by ydhuang28** [comment]
This isn't implemented yet. Right now all models are plotted if they have data submitted. @nickreich should we implement this based on the "primary" designation?

**Comment by nickreich** [comment]
Seems like there is some selection going on somewhere. E.g. not all the `CU` models are shown in the viz:
![image](https://user-images.githubusercontent.com/1280767/97622931-547e9680-19fb-11eb-8025-3f35abd88ba4.png)

**Comment by nickreich** [comment]
I think what we want is all models that are "primary" and "secondary" being shown. but "other" models should be left off.

**Comment by ydhuang28** [comment]
Hmm. @hannanabdul55 @Khoale1096 do you guys remember/know where this is done in the code?

**Comment by ydhuang28** [comment]
Closing this. As a reference, models that are designated as "primary" or "secondary" will be plotted, others will not.
