### ISSUE TITLE
Negative values in covid19-forecast-hub/data-truth/truth-Incident Cases.csv

### ISSUE THREAD

**Issue by mab-az** [reichlab/covid19-forecast-hub#3652]
Should there be negative values? What do those negative values mean?

for example:
2021-04-02, 01003, Baldwin County, **-4**

**Comment by ydhuang28** [comment]
Usually, this indicates that there was a revision in observed truth data, and subsequently, the number of cases for a given location decreased for a given time point. We acquire our truth data from [JHU's CSSE group](https://github.com/CSSEGISandData/COVID-19/), so any truth data issue is best taken up with them. Sorry for the delayed reply!
