### ISSUE TITLE
determine feasibility of including additional targets in visualization

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#37]
Could we use the drop-down menu that we have previously used for "season" to toggle between different forecast targets, e.g. incident deaths, cumulative deaths, hospitalizations, etc...? how much customization would this take?

**Comment by katiehouse3** [comment]
I will look into this next week - best guess is a few days to get it running!

**Comment by katiehouse3** [comment]
- [ ] 5-6 ahead targets to current visualization?
- [ ]  add the incident deaths plot?
- [ ] daily scale?

**Comment by jarad** [comment]
This is the main feature I would like to see implemented.
