### ISSUE TITLE
reorder validation tests

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#395]
@jarad asks: Can we switch the order of the tests so that the "invalid target" test comes before the "target_end_date" test?

@matthewcornell asks: could you give some general thought to prioritization and provide some guidance (say as simple rules)

can we think more generally about how to order the tests and whether there should be a prioritization?

**Comment by jarad** [comment]
I've started updating the [validation wiki](https://github.com/reichlab/covid19-forecast-hub/wiki/Validation-Checks) such that the order indicated on the wiki is the order that, I think, makes logical sense.

**Comment by matthewcornell** [comment]
It sounds like we are talking about the ordering of error messages in reports rather than the ordering of the actual checks, correct? The latter should not matter if we are smart about ordering the errors that are returned for the report.

To this end, would it be useful to categorize the validations in the wiki page @jarad links to? Two "levels" might make sense (WARNING or ERROR, say), which would be used to sort the per-file messages.

Thoughts?

**Comment by jarad** [comment]
I agree that I am thinking about the order of the error messages (which I was equating to the order of the checks). For me all the checks in the wiki should produce errors rather than warnings. Which did you think should be warnings?

**Comment by matthewcornell** [comment]
Sorry, my point was to connect levels with output ordering, where the highest-level items would be listed first in the output. Call them priorities, if that makes more sense. Say, "1" and "2". All the "1s" would be reported/listed first, followed by the "2s".

?

**Comment by jarad** [comment]
Gotcha. That makes sense. With that being said, we also group by metadata vs forecast checks.

**Comment by matthewcornell** [comment]
@jarad What I need from you in order to move forward is a categorization of the messages, at a minimum binary ("high" or "low"), or as many categories as you want to group by. Then I can sort them by category.

**Comment by nickreich** [comment]
Adding @hannanabdul55 to this thread. 
@matthewcornell says that he will order the messages by the order of the list of current validations on the wiki. But his checks don't handle the metadata checks at all, that is managed "locally" by Travis. So maybe @hannanabdul55 can ensure that any metadata error messages would appear before the forecast error messages.

**Comment by matthewcornell** [comment]
After talking w/ @nickreich I believe I understand what to do: I will order the output messages in the four groups (the last four bullets, and not the _metadata checks_) in the order of the *Current Validation checks* section of the wiki page.
