### ISSUE TITLE
Fix model ordering when switching between visualization views (e.g. incident and cumulative)

### ISSUE THREAD

**Issue by jarad** [reichlab/covid19-forecast-hub#397]
When select "Incident Deaths", the COVIDhub-ensemble model and other models disappear from the list of models. These models do NOT reappear when selecting "Cumulative Deaths". I believe they should reappear when selecting "Cumulative Deaths". 

There is perhaps a larger question here of what set of models should be shown. Should we only show the set of models that are available for a particular location-target combination? How do we decide what set of models are selected as you click to different locations and targets?

**Comment by jarad** [comment]
The models do reappear but they reappear at the end of the list.

**Comment by hannanabdul55** [comment]
This does not happen now. The order remains the same.
