### ISSUE TITLE
change date alignment of incident deaths

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#403]
right now incident and cumulative deaths for week w are aligned with the first day of week w+1. 

This make sense for cumulative deaths for week w, since that really represents deaths at the END OF week w. 

But for incident deaths, I think it would make more sense to align the counts for week w with week w and not w+1. 

@katiehouse3 does this make sense to you?

**Comment by mzorn-58** [comment]
@nickreich Can we close this issue?

**Comment by nickreich** [comment]
this issue should remain open. it actually came up with CDC recently in a conversation about aligning epiweeks. i will try to fit it into an agenda with them and will report back.

**Comment by ydhuang28** [comment]
@nickreich was this issue investigated further? Trying to decide whether this would need to be incorporated into viz v2.
