### ISSUE TITLE
Automate delete of forecast/model on Zoltar if it's removed from github repo

### ISSUE THREAD

**Issue by Khoale1096** [reichlab/covid19-forecast-hub#405]

**Comment by nickreich** [comment]
@Khoale1096 has this been finished? if not, can you provide a quick status update here?

**Comment by Khoale1096** [comment]
I worked on this last month before my internship, but didn't get it finished yet since at that time I believe this was a low priority issue. It seems like that has change as of now. The code for deleting is done, but I would like to configure it to be separate from the uploading part. I'm thinking of a CRON job that checks every day if there's any forecasts on Zoltar that is not on github repo, then send a delete request.

**Comment by nickreich** [comment]
@hannanabdul55 can you remind me what we did when we migrated the files to the new format and switched target definitions in the summer. some files were removed from the repo, right? are these still on Zoltar?

**Comment by hannanabdul55** [comment]
When we migrated the files to the new format, we had to rename some of the forecast files. hence, we had to rename the `source` field of that forecast file also to the renamed value. We did not technically remove any forecasts when we did the migration, just renamed some of them.

**Comment by nickreich** [comment]
but werent there some that didn't have any valid rows remaining once we removed the day ahead death targets?

**Comment by hannanabdul55** [comment]
Oh yes, that is correct. You're right. We removed them from our repository. But I think they're still there in Zoltar. We did not remove them from there.
