### ISSUE TITLE
drake::r_make error for the past 4 or so weeks (today is July 24, 2021)

### ISSUE THREAD

**Issue by jjdfsny** [reichlab/covid19-forecast-hub#4388]
Hello.  The drake::r_make("code/shiny/_drake.R") process has worked for me up until about 4 weeks ago.  Here is the error (is the problem at my end? - thanks! - R 4.0.3 and Rstudio Version 1.4.1106):

  latest_plot_data_by_model_latest_forecasts_.UVA.Ensemble._, 
    latest_plot_data_by_model_latest_forecasts_.Wadhwani_AI.BayesOpt._, 
    latest_plot_data_by_model_latest_forecasts_.WalmartLabsML.LogForecasting._, 
    latest_plot_data_by_model_latest_forecasts_.Yu_Group.CLEP._, 
    latest_plot_data_by_model_latest_forecasts_.YYG.ParamSearch._)
  vctrs::vec_rbind(!!!dots, .names_to = .id)
  (function () 
vec_default_ptype2(x = x, y = y, x_arg = x_arg, y_arg = y_arg, 
    `vctrs:::from_dispatch` = `vctrs:::from_dispatch`, `vctrs:::df_fallback` = `vctrs:::df_fallback`, 
    `vctrs:::s3_fallback` = `vctrs:::s3_fallback`))()
  vctrs::vec_default_ptype2(x = x, y = y, x_arg = x_arg, y_arg = y_arg, 
    `vctrs:::from_dispatch` = `vctrs:::from_dispatch`, `vctrs:::df_fallback` = `vctrs:::df_fallback`, 
    `vctrs:::s3_fallback` = `vctrs:::s3_fallback`)
  vctrs::stop_incompatible_type(x, y, x_arg = x_arg, y_arg = y_arg, 
    `vctrs:::from_dispatch` = match_from_dispatch(...))
  vctrs:::stop_incompatible(x, y, x_arg = x_arg, y_arg = y_arg, 
    details = details, ..., message = message, class = c(class, 
        "vctrs_error_incompatible_type"))
  vctrs:::stop_vctrs(message, class = c(class, "vctrs_error_incompatible"), 
    x = x, y = y, details = details, ...)
  rlang::abort(message, class = c(class, "vctrs_error"), ...)
  rlang:::signal_abort(cnd)
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Error: callr subprocess failed: target latest_plot_data failed.
diagnose(latest_plot_data)$error$message:
  Can't combine `..1$0.025` <double> and `..59$0.025` <character>.
diagnose(latest_plot_data)$error$calls:
  dplyr::bind_rows(latest_plot_data_by_model_latest_forecasts_.AIpert.pwllnod._, 
    latest_plot_data_by_model_latest_forecasts_.Auquan.SEIR._, 
    latest_plot_data_by_model_latest_forecasts_.BPagano.RtDriven._, 
    latest_plot_data_by_model_latest_forecasts_.Caltech.CS156._, 
    latest_plot_data_by_model_latest_forecasts_.CDDEP.SEIR_MCMC._, 
    latest_plot_data_by_model_latest_forecasts_.CEID.Walk._, 
    latest_plot_data_by_model_latest_forecasts_.CMU.TimeSeries._, 
    latest_plot_data_by_model_latest_forecasts_.Columbia_UNC.SurvCon._, 
    latest_plot_data_by_model_latest_forecasts_.Covid19Sim.Simulator._, 
    latest_plot_data_by_model_latest_forecasts_.CovidActNow.SEIR_CAN._, 
    latest_plot_d
[...]

**Comment by jjdfsny** [comment]
the error really says this with "<double>" after the ..1$0.025 and "<character>" after the ..59$0.025

Error: callr subprocess failed: target latest_plot_data failed.
diagnose(latest_plot_data)$error$message:
  Can't combine `..1$0.025` <double> and `..59$0.025` <character>.

**Comment by jjdfsny** [comment]
Obviously I am having trouble inserting code:

`Error: callr subprocess failed: target latest_plot_data failed.
diagnose(latest_plot_data)$error$message:
  Can't combine `..1$0.025` <double> and `..59$0.025` <character>.
`

**Comment by nickreich** [comment]
@jjdfsny we haven't explicitly supported the drake functionality for a long time. are you using covidhubutils? that is our recommended way of working with the Hub data:
https://github.com/reichlab/covidhubutils

**Comment by jjdfsny** [comment]
Thank you!  Jim Jarratt
