### ISSUE TITLE
make shiny app more lightweight and loading faster

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#440]
Maybe re-create some of the tabs only on-demand? or otherwise do something to make it load faster and be more responsive. E.g. the "all data" tab basically is so slow that it doesn't work right now.

**Comment by jarad** [comment]
Considering using [drake](https://github.com/ropensci/drake) to speed up pre-processing of data.

**Comment by jarad** [comment]
Probably the "all" tab will need to go, unless somebody knows how we can speed up display of a large table.

**Comment by jarad** [comment]
@Serena-Wang Let's remove the "Latest" tab and use `data.table::fread` to read in all csv files.

**Comment by nickreich** [comment]
I think this issue is defunct and could be replaced by more specific and current issues.
