### ISSUE TITLE
Clean up dist folder everytime a new visualization is built.

### ISSUE THREAD

**Issue by hannanabdul55** [reichlab/covid19-forecast-hub#445]
## Issue: 
Currently, the build adds new files to the `dist` folder but does not delete the old files from the previous build. As a result of this, the `dist` folder keeps increasing in size with every build. 

## Potential fix
- The fix would be to just delete the `dist` folder completed before any build. 
- Another would be to just remove the `dist` folder completely from the git folder as it is a generated folder of the build. 

## Downstream tasks
- Maybe also clean up the `gh-pages` branch also as it has a LOT of old unused files. Hence, this also increases deployment time for a relatively simple website.

**Comment by nickreich** [comment]
if we removed dist entirely, would it still be possible for people to "view locally" the already built visualization?
Definitely makes sense to at least delete old files.

**Comment by hannanabdul55** [comment]
Yes, we would not be able to view locally in that case. But I was thinking of other ideas to have a "staging" branch, which would have the local visualization changes. I created this issue to start a discussion around this.

**Comment by hannanabdul55** [comment]
This(https://github.com/reichlab/covid19-forecast-hub/commit/30de40678196bee6f2894d7d037be7b58a864dc9 ) commit on master removes the old files and has the latest local build in the `dist` folder. 
- Verified that the visualization does not break with this. 
- This is done only on the local visualization code in the master branch (`gh-pages` is still the same). 
- I had to commit directly instead of getting it reviewed in a PR because there were so many old files that had to be deleted that GitHub could not perform a diff.

**Comment by hannanabdul55** [comment]
Closing this PR. As this is done.
