### ISSUE TITLE
Add current hospitalization target

### ISSUE THREAD

**Issue by jarad** [reichlab/covid19-forecast-hub#453]
Currently our [hospitalization target](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md#n-day-ahead-inc-hosp) is new daily hospitalizations. We should consider adding a current hospitalization targets. We may want to change the names to "hosp-new" and "hosp-current".

**Comment by nickreich** [comment]
I think we have to be very careful about adding new targets. Our storage capacity is straining at the seams right now, both on GitHub and Zoltar. We made a decision early to include "new" hospitalizations with the thought that "current" hospitalizations could be backed out of that pretty easily with some basic assumptions (e.g. 10 day duration of hospitalization).
