### ISSUE TITLE
re-format layout of TimeChart

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#461]
- [ ] move the legend to the left hand side of the figure (i.e. the left-hand side of the legend would be aligned with 2020-01-01 or thereabouts)
 - [ ] shorten the x-axis so that instead of going through December 2020, it goes only through the last `target_end_date` of any forecast?

**Comment by jarad** [comment]
Looks like this has been completed to me. @nickreich

**Comment by jarad** [comment]
With the x-axis ending 4 weeks out, the tooltip is cutoff for me so that I can't see the information in week 3 or week 4 ahead.
