### ISSUE TITLE
Update Travis credentials for pushing to GitHub

### ISSUE THREAD

**Issue by Khoale1096** [reichlab/covid19-forecast-hub#462]
Travis is error-ing when running `travis/push.sh` because Katie's credentials are removed when she left I think. We need to update this for Travis to be able to push its changes (code/validation/validated_files.csv for example) to GitHub. You can find the error in one of the [build](https://travis-ci.com/github/reichlab/covid19-forecast-hub/builds/169673217) (the build itself did not return an error though)
<img width="629" alt="Screenshot (404)" src="https://user-images.githubusercontent.com/31902663/83897259-5c276100-a723-11ea-9d79-5738b79836c7.png">

**Comment by hannanabdul55** [comment]
Just fixed this and travis builds are now passing again 🚀
