### ISSUE TITLE
revise metadata team name and model name checks

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#479]
1. team_abbr must be unique.
2. model_abbr must be unique within a given team. Equivalenly, as long as we rely on #1 being checked, we could specify that the combination of [team_abbr]-[model_abbr] must be unique across the entire project.

**Comment by jarad** [comment]
I don't think we can enforce 1. as a check. `team_abbr` is related to a directory, but what is different from a team adding a new directory vs a new team adding a directory.

**Comment by nickreich** [comment]
I don't understand your question. why can't we enforce this?

**Comment by jarad** [comment]
To be clear, I said we can't enforce this "as a check", i.e. automatically. We can certainly enforce this by looking at the submission files. 

Imagine a `team_abbr` "A" with a current model "M1" such that there is a directory "A-M1/". Now that team wants to add a new model "M2" so they create a new directory "A-M2/". So far we have allowed this. Now there is a different team and they like the `team_abbr` "A" and they have a model "N1", so they create a directory "A-N1". I don't think we want to allow them to do this. But there is no (clear to me) way to distinguish these two situations.
