### ISSUE TITLE
metadata updates for zoltar

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#510]
which metadata field is the authoritative "link" for a model? This should be the link that goes into the Zoltar "home" field for a model. Currently it is the link to the home folder for that particular model on our GitHub repo. So the two tasks for this issue are:
 - [x] update all current "home" links in Zoltar to point to available urls in metadata files
 - [x] update zoltar model creation script to have this link from metadata be added by default

@Khoale1096 can you comment here on where the relevant script is that needs to be updated?

**Comment by Khoale1096** [comment]
Update: 1st task (update all current "home" links in Zoltar) is done for any model that provides "model_repo" in its metadata

**Comment by nickreich** [comment]
awesome, thanks @Khoale1096 !

**Comment by hannanabdul55** [comment]
@nickreich I am done with this change for 1st task. Just an aside: Do we want to make the `model_repo` field mandatory?

**Comment by hannanabdul55** [comment]
Please review #534  and let me know. Thanks!

**Comment by nickreich** [comment]
we may need to update based on #456

**Comment by hannanabdul55** [comment]
reopening this for #456

**Comment by hannanabdul55** [comment]
Can close this now since #456  is closed now.
