### ISSUE TITLE
stray arrow appears in county level plot

### ISSUE THREAD

**Issue by mzorn-58** [reichlab/covid19-forecast-hub#5274]
When running [code/reports/all-states-weekly-report.Rmd](code/reports/all-states-weekly-report.Rmd) a stray arrow appears in county-level plot if using plotly package 4.10.0, but does not appear when using  plotly package 4.9.4.1.  

Using plotly 4.9.4.1

![image](https://user-images.githubusercontent.com/66443989/140403148-683aa396-b656-4edb-bc5d-4d7a2d7f9391.png)

Using plotly 4.10.0
![image](https://user-images.githubusercontent.com/66443989/140407017-8f2b5c35-4d75-4815-a811-70b197bd4d4b.png)

We will plan to use plotly 4.9.4.1 when running the weekly report until this is figured out.

**Comment by nickreich** [comment]
no more county plots
