### ISSUE TITLE
latest/ihme-covid19.zip is 0 bytes in size

### ISSUE THREAD

**Issue by NGeorgescu** [reichlab/covid19-forecast-hub#5400]
There appears to be some issue with this file:

https://ihmecovid19storage.blob.core.windows.net/latest/ihme-covid19.zip

Thanks!

**Comment by nickreich** [comment]
is the linked file related to this repo at all? closing for now, feel free to repoen if you have additional questions.

**Comment by NGeorgescu** [comment]
Ah sorry. I thought they were. This issue resolved itself anyhow. 

Thanks,
NSG
