### ISSUE TITLE
'Run failed: Trigger zoltar upload' messages

### ISSUE THREAD

**Issue by tkcy** [reichlab/covid19-forecast-hub#5453]
Happy Thanksgiving! This is not at all urgent so please wait until Monday to respond - I'm just writing now because I have some down time.

Since I did the 'Fetch and Merge' last week, I've been getting emails every few hours saying:
Run failed: Trigger zoltar upload - master (28eb9d2)

I'm not sure what it's referring to.  Can I make this stop without just disabling my github alerts altogether? 

Thanks!

**Comment by nickreich** [comment]
I think what is happening is that your fork of the repo is trying to run the github actions that are configured to run only on the main repo. I think there is a way to go to your clone of the repository, go to the actions tab and "turn off" the actions somehow.

**Comment by nickreich** [comment]
Closing this issue, but if you continue to have the issue, please reopen. thanks!
