### ISSUE TITLE
Bad link to FIPS location

### ISSUE THREAD

**Issue by youyanggu** [reichlab/covid19-forecast-hub#560]
There are two bad links to the FIPS file on the Technical README page: https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md#location

The current link is https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/data-locations/locations.csv, I believe it should be https://github.com/reichlab/covid19-forecast-hub/blob/master/data-locations/locations.csv

**Comment by hannanabdul55** [comment]
Thank you for reporting this! They've been fixed in https://github.com/reichlab/covid19-forecast-hub/commit/2988ec05ba8fad12d040686ef07bd998b3aa02d3 .
