### ISSUE TITLE
Update metadata checks wiki

### ISSUE THREAD

**Issue by jarad** [reichlab/covid19-forecast-hub#573]
The [metadata checks wiki](https://github.com/reichlab/covid19-forecast-hub/wiki/Metadata-Checks) needs to be updated with the checks we are actually doing.

**Comment by hannanabdul55** [comment]
Updated the wiki. Please check : https://github.com/reichlab/covid19-forecast-hub/wiki/Metadata-Checks

**Comment by jarad** [comment]
Seems like there is more updating to do, e.g. `team_abbr` and `model_abbr` both must be less than 15 characters.

**Comment by hannanabdul55** [comment]
Those are specified in the metadata format page that is specified at the beginning of https://github.com/reichlab/covid19-forecast-hub/wiki/Metadata-Checks . Closing this as it is done.
