### ISSUE TITLE
add instructions for running the visualization locally to the wiki

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#58]

**Comment by katiehouse3** [comment]
I have instructions here: https://github.com/reichlab/covid19-forecast-hub/tree/master/visualization Should I move these to the wiki? and perhaps elaborate more?

**Comment by nickreich** [comment]
yes and yes. :-)

**Comment by katiehouse3** [comment]
@nickreich Could you try these steps and let me know if this is sufficient? https://github.com/reichlab/covid19-forecast-hub/wiki/Interactive-Visualization#step-0-one-time-setup-on-mac

**Comment by katiehouse3** [comment]
Closing this for now. I'll reopen if users are still having issues.
