### ISSUE TITLE
have model_abbr metadata field be [team_abbr]-[model_abbr]

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#599]
This would bring us in sync with Zoltar and creates a single unique identifying field in the metadata.

Would require us to also modify validation code to use the new `[model_abbr]` and not the old `[team_name]-[model_abbr]`

**Comment by nickreich** [comment]
The specific proposal here is to remove the `team_abbr` field and have the udpated `model_abbr` field be a merger so that it is `[team_abbr]-[model_abbr]`. 

@jarad wanted to flag you so you saw we are thinking about doing this. it came up today in a conversation with @matthewcornell and @hannanabdul55 when discussing synchronization between zoltar and github metadata. Any thoughts or comments? clearly not ideal to make this one additional change to metadata, but I also think it makes sense to do, and we remove one required metadata field and create a single unique ID in metadata, which we currently don't have.

**Comment by jarad** [comment]
Sorry for my delay. I don't have any objection to this. Do we want to just call this field `model`?

**Comment by hannanabdul55** [comment]
Fixed.
