### ISSUE TITLE
CDC website requirements

### ISSUE THREAD

**Issue by josh-wilde** [reichlab/covid19-forecast-hub#628]
hi @nickreich, apologies if this is the wrong venue for this question- MIT has restricted joining Google Groups under the contact email address that I provided. In a prior message you said that as long as we have a forecast on the website with a forecast date of Friday-Monday, then we should be included automatically. Does this mean that the CDC has regular weekly update schedule for including new models and predictions? If so, do you know which day(s) of the week this process runs? Thanks for the help!

**Comment by nickreich** [comment]
can you please send me an email? nick@schoolph.umass.edu
