### ISSUE TITLE
Rescale y-axis based on current model selection

### ISSUE THREAD

**Issue by hannanabdul55** [reichlab/covid19-forecast-hub#634]
From @elray1 : 

> Would it be possible to rescale the vertical axis based on only the models that are currently selected?  

Based on the models,  adjust the range of the y-axis to to make the graph more readable.

**Comment by nickreich** [comment]
Here are a few specific thoughts, to operationalize this change. Throughout, I'm going to use the term `ymax` to refer to the maximum limit on the y-axis.

option A: make `ymax` = {maximum value of [ (currently plotted observed values) AND (point estimates of all forecasts, selected and not, for the current week) ] } * \alpha, where \alpha is a constant, perhaps 1.2.

option B: make `ymax` = {maximum value of [ (currently plotted observed values) AND (point estimates of all selected forecasts for the current week) ] } * \alpha. This would then lead to possible axis updates whenever a new model was selected, which might feel "jumpy". So I'd prefer option A over B.

option C: implement one of A or B and then have a dynamically changeable y-axis. This feels more complicated to me, but perhaps there could be a zoom in/out feature we could implement via D3? They must have something like this. My preference again might be to try to implement something like option A and then consider this as a separate issue.

**Comment by hannanabdul55** [comment]
implemented in https://github.com/reichlab/covid19-forecast-hub/tree/rescale-y

**Comment by hannanabdul55** [comment]
@nickreich can we close this issue now?
