### ISSUE TITLE
Would like push access to add new model

### ISSUE THREAD

**Issue by RobertWalraven** [reichlab/covid19-forecast-hub#644]
I have developed a new empirical COVID-19 model and I would like to  upload predictions to your repository to be considered for inclusion in the ensemble.   Would you please add a folder "RobertWalraven-ESG" to the data_processed area and grant me push access?   My email address is Walraven@multiwareinc.com.

**Comment by nickreich** [comment]
We don't give contributors push access, but anyone is able to submit a pull request. Please do this and a series of checks/validations will be run on the submitted data. Thanks!
