### ISSUE TITLE
Standardize processed data filenames

### ISSUE THREAD

**Issue by jarad** [reichlab/covid19-forecast-hub#67]
In addition to the missing fields in #66, the newest [MOBS processed data file](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/MOBS_NEU-GLEAM_COVID/2020-04-27-MOBS_NEU-GLEAM-COVID-19_v1.csv) has a filename that is non-standard (for me) and is causing me issues with [reading  processed data](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/read_processed_data.R) for the [shiny data-processing app](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/explore_processed_data.R).

Although I could update the data reading script, I think the real issue is that we don't seem to have a standardized filename processed data. I was assuming "-" was a reserved character such that the files are named

YYYY-MM-DD-team-model.csv

Can we set this as a standard?

**Comment by katiehouse3** [comment]
Added the script: https://github.com/reichlab/covid19-forecast-hub/blob/master/code/validation/validate_filenames.R now need to automate with Travis (may take a bit to get Packrat up and running)

**Comment by katiehouse3** [comment]
Never mind my script had no libraries. Checks are complete with Travis https://travis-ci.com/github/reichlab/covid19-forecast-hub
