### ISSUE TITLE
add check: any number in `value` column of submission should be >=0

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#688]

**Comment by nickreich** [comment]
this applies to both cumulative and incident deaths

**Comment by nickreich** [comment]
some negative values in, e.g., this file: https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/USC-SI_kJalpha/2020-06-23-USC-SI_kJalpha.csv

**Comment by matthewcornell** [comment]
@nick you corrected to: https://raw.githubusercontent.com/reichlab/covid19-forecast-hub/master/data-processed/USC-SI_kJalpha/2020-06-21-USC-SI_kJalpha.csv
