### ISSUE TITLE
change Zoltar target definitions to include lower bound of 0

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#690]

**Comment by jarad** [comment]
@matthewcornell We're are thinking this issue is fixed. If yes, can you close it?

**Comment by matthewcornell** [comment]
@nickreich Can we talk about this? I don't remember the details. I'm guessing this means add a range to all the "COVID-19 Forecasts" Zoltar project targets. Did we ever support open-ended ranges, such as [0, +Inf]?

**Comment by nickreich** [comment]
I think we don't need to do this, since we are for now accepting the fact that sometimes truth data is actually negative.
