### ISSUE TITLE
consolidate state_fips_codes.csv and locations.csv

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/covid19-forecast-hub#692]
`template/state_fips_codes.csv`: columns: `state,state_code,state_name`
`data-locations/locations.csv`: columns: `abbreviation,location,location_name`

We should consolidate into: `data-locations/locations.csv`

**Comment by jarad** [comment]
@matthewcornell Can you list the files that use the state_fips_codes.csv file?

**Comment by matthewcornell** [comment]
code/ensemble-scripts/component_check.R
code/ensemble-scripts/ew_quantile.R

**Comment by nickreich** [comment]
Those files above in the code/ensemble-scripts folder have been delted.

**Comment by nickreich** [comment]
@jarad should I also now delete the state_fips_codes.csv file and close the issue?
