### ISSUE TITLE
Clarification of data submission instructions

### ISSUE THREAD

**Issue by RobertWalraven** [reichlab/covid19-forecast-hub#694]
The target "N wk ahead inc case" is defined as the number of new cases reported by JHU CSSE.   However, in the quantile section this target says that values should be provided for the 6-member quantile list, which implies what you actually want is a model prediction, not the number of JHU CSSE reported new cases.   Is that correct?

**Comment by nickreich** [comment]
Yes, we want a prediction like the other targets not just the number. we will clarify this in the README.

**Comment by jarad** [comment]
Hoping the new wording is more clear.
