### ISSUE TITLE
update FIPS codes

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#698]

**Comment by eycramer** [comment]
Updated fips codes to match [https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv)
