### ISSUE TITLE
County-wide forecast question

### ISSUE THREAD

**Issue by RobertWalraven** [reichlab/covid19-forecast-hub#699]
For the new county-level forecasts we are suppose to only consider counties with populations > 50,000, presumably because forecasts may not be reliable for smaller counties.   But even with this limit there are many counties where the number of deaths is very low, sometimes even just 1 death.   I'm not sure how any kind of reliable prediction can be made if there are just a small number of deaths in a county.   I understand that some models may predict deaths using some confirmed data, but I'm wondering if there is some concensus on how many cumulative deaths are needed to make reliable projections.   In my own state and country analysis I typically don't consider predictions if there are fewer than 20 deaths.

**Comment by jarad** [comment]
To be clear, we are requesting **case** forecasts for **all** counties. No, I don't think there is any concensus on how many cumulative deaths are needed to make reliable projections. As different teams are using vastly different data, it may be that some teams are able to make accurate predictions even when the counts are low. Only time will tell.
