### ISSUE TITLE
MIgration of forecast files to new format

### ISSUE THREAD

**Issue by hannanabdul55** [reichlab/covid19-forecast-hub#706]
## Description  
Write a script to migrate forecasts from one version to another.  
- Currently, we require each forecast file to only has the columns: `['location', 'target', 'type', 'quantile', 'value', 'forecast_date', 'target_end_date']`. 
- Write a script to make these changes.

**Comment by nickreich** [comment]
@hannanabdul55  this is not quite right. There are two additional required columns: `forecast_date` and `target_end_date`. They are not required for Zoltar, but are required for the Hub. Documentation here:
https://github.com/reichlab/covid19-forecast-hub/tree/master/data-processed#forecast-file-format

**Comment by hannanabdul55** [comment]
Oops. Yeah, you're right. I just took this from the document. editing this issue to add that 👍

**Comment by hannanabdul55** [comment]
Closing this issue and this is done.
