### ISSUE TITLE
Unable to pass the validation test with county-level forecast

### ISSUE THREAD

**Issue by FrostXTJ** [reichlab/covid19-forecast-hub#716]
Hi,

Our team is trying to submit a forecast file that includes county-level predictions. We are using the FIPS code from `locations.csv` as each county's `location`, but our file is unable to pass your validation script(we run `test-formatting.py` locally). Following errors are given:

```
invalid FIPS location: '10001'. row=['2020-07-05', '1 wk ahead cum death', '2020-07-11', '10001', 'point', 'NA', '95.0245762676546']
invalid FIPS location: '10001'. row=['2020-07-05', '2 wk ahead cum death', '2020-07-18', '10001', 'point', 'NA', '98.6415319559387']
......
invalid FIPS locatio...
``` 

This is not just complaining about region `10001` because I tried removing this county in our report, and the validation test will continue to complain about `10003`. I wonder if you can fix the validation script? Thank you!

**Comment by nickreich** [comment]
Yes, as we said in our email, new forecasts will fail until we update this today. We will be re-running the checks once the validations are updated. Stay tuned.

**Comment by hannanabdul55** [comment]
I think this is fixed. Closing this.
