### ISSUE TITLE
First-Time Pull Request

### ISSUE THREAD

**Issue by scorsett** [reichlab/covid19-forecast-hub#722]
Hi,

My team is working on creating our first pull request, and we are having a bit of trouble getting started. We are under the impression that we must create a new branch in order to make requests. However, we are getting "access denied" errors when we attempt this. Is there a specific pre-existing branch that we should be using for our request?

Thanks!

**Comment by nickreich** [comment]
Hi @scorsett, thanks for your participation! You need to fork this main repository to your own GitHub account, then you can push files into the `master` branch of the `scorsett/covid19-forecast-hub/` and then submit a PR to merge that branch with the `master` branch of the `reichlab/covid19-forecast-hub`.

**Comment by scorsett** [comment]
Hi @nickreich, thank you for the information! My team has been able to create a pull request.
