### ISSUE TITLE
Separate forecasts from truth

### ISSUE THREAD

**Issue by jarad** [reichlab/covid19-forecast-hub#76]
I suggest we reorganize the data so that forecasts are separate from truth, e.g. 

data-raw/forecasts
data-raw/truth
data-processed/forecasts
data-processed/truth

The subdirectory structure within the forecasts/ subdirectories would be the same as it is now. 

Also, perhaps we should include nytimes "gold-standard" data in addition to the JHU data.

**Comment by nickreich** [comment]
I think this is a reasonable idea, keeps things nicely organized. @katiehouse3 are there other downstream implications for this?

**Comment by nickreich** [comment]
Let's make a separate subfolder for `data-processed/truth` and `data-raw/truth`.

**Comment by katiehouse3** [comment]
Done!
