### ISSUE TITLE
Fix names in locations.csv

### ISSUE THREAD

**Issue by jarad** [reichlab/covid19-forecast-hub#761]
Now that we have added counties, we need to determine how to set `location_name` and possibly add additional fields, e.g. `county` and `state` in [location.csv](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-locations/locations.csv).

**Comment by eycramer** [comment]
Would it helpful to just add the word "county" to the location_names for each county?  (ex. Cook County vs. just "Cook")

**Comment by hannanabdul55** [comment]
Yes, we very much need this as the truth data script kinda got messed up because of this. It is fixed as of now, but this would help us remove the temporary fix that was put in place.

**Comment by eycramer** [comment]
Ok I can take care of that. Will changing the location_name lead to any other issues I should be aware of? Or it is ok for me to change them?

**Comment by hannanabdul55** [comment]
You would change the location_name only for counties, right?

**Comment by eycramer** [comment]
Yes

**Comment by hannanabdul55** [comment]
Then I think it is fine 👍

**Comment by eycramer** [comment]
Added county names to locations.csv
