### ISSUE TITLE
Truth data minor issue

### ISSUE THREAD

**Issue by RobertWalraven** [reichlab/covid19-forecast-hub#818]
The truth incident data starts one day later on 1/23 than the truth cumulative data, which starts on 1/22.   I know that the data is zero for all locations on both dates, but the minor discrepancy means the tables don't line up.

**Comment by nickreich** [comment]
@RobertWalraven can you confirm if this is the JHU truth data or one of the other (NYT, USAFacts).

**Comment by RobertWalraven** [comment]
The two csv files at https://github.com/reichlab/covid19-forecast-hub/tree/master/data-truth.

**Comment by RobertWalraven** [comment]
Now that case truth tables has been added, there is an additional discrepancy in starting dates, which are
Cumulativecases:  1/23
CumulativeDeaths:  1/22
IncidentCases:  1/24
IncidentDeaths: 1/23
Since the data for January is 0 for all states, this difference in starting dates is not significant, but it might cause some confusion for new teams if they assume all four sets of data have the same starting date like I did.

**Comment by nickreich** [comment]
The JHU CSSE data should be used as the ground truth data for all modeling efforts. We reproduce the data here for convenience for some of our internal purposes.
