### ISSUE TITLE
Submissions are not being included in the ensemble

### ISSUE THREAD

**Issue by maa989** [reichlab/covid19-forecast-hub#8874]
Hello, 

It seems our submissions for the SGroup-RandomForest model have not been included in the ensemble for the last several weeks with the comment “missing required forecasts” for all the locations. We have been submitting our forecasts every week and all checks have been passing like usual, can someone give us more details to why this is happening now? 

Thanks.

**Comment by nickreich** [comment]
I'm not 100% sure, but a quick look at this suggests that maybe you are not submitting forecasts for all 28 days ahead (maybe just 24?). 28 days are required to be part of the 4-week ahead ensemble, as explained in the [detailed eligibility criteria](https://covid19forecasthub.org/doc/ensemble/). It looks like in mid-June your team switched from 28 to 24 day ahead as the maximum horizon. This is visible in [this visualization of the submitted forecasts](https://zoltardata.com/project/44/forecasts?color_by=targets&target=day+ahead+incident+hospitalizations&date_range=2023-05-01+to+2023-09-23&min_num_forecasts=15)
