### ISSUE TITLE
Sum of county deaths does not equal state deaths in truth data

### ISSUE THREAD

**Issue by RobertWalraven** [reichlab/covid19-forecast-hub#899]
In the Truth data there are some states where the inc deaths does not equal the sum of the county inc deaths for that state.   The worst case is Rhode Island, which showed inc truth deaths for all five counties to be zero whereas the state data showed significant non-zero inc values and a cumulative value of 990 on 7/20.  The cause of this discrepancy is due to two categories being omitted from the county information:  Out of <state> and Unassigned, both of which have separate FIPS codes for each state.

This caused me some confusion as I was using the JHU data for analysis, which includes the two additional state FIPS codes and compared my results to the truth data from this site, because the results did not align for several states.

I suggest the out of state and unassigned data be included in the truth data to make the state and county data consistent with each other.

**Comment by hannanabdul55** [comment]
Interesting. Thank you for reporting this! 
Yes, I guess we can do that, what say @nickreich ?

**Comment by jarad** [comment]
My understanding is that this occurs because there are non-county locations that are included in state totals, although I don't have a specific example. Thus, we have no plans to change the data. We are working on wording to make it clear why this occurs.

**Comment by RobertWalraven** [comment]
So you are ok with reporting no deaths at the county level for Rhode Island because all the death data is in the "Unassigned" FIPS category for Rhode Island, which you don't include?

**Comment by jarad** [comment]
We're more than happy to merge a pull request that addresses this.
