### ISSUE TITLE
Double entry for DC (FIPS 11001) in JHU truth data

### ISSUE THREAD

**Issue by RobertWalraven** [reichlab/covid19-forecast-hub#903]
There are double entries for the District of Columbia FIPS code 11001 in all four truth tables.   The extraneous entry is in the top section where the state totals are listed.   Right after the code 11 for the District of Columbia you will see an entry 11001, which should not be there because it also appears in the lower section where the county data is located.

When applications read these files the numbers for the District of Columbia will probably end up being doubled unless there is a specific check for duplicate entries.

I recommend the erroneous entry 11001 in the upper section of these files be removed.

**Comment by Serena-Wang** [comment]
Hi @RobertWalraven,

Thanks for pointing that out. Now we've removed 11001 in those four truth tables.
