### ISSUE TITLE
not all day-ahead targets are showing up in shiny app

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#91]
@jarad I see up to 41 day ahead targets in the recent 2020-04-26 CU files, but only max_n=9 for the day_ahead targets in the app.

**Comment by nickreich** [comment]
![image](https://user-images.githubusercontent.com/1280767/80440022-d4edfe80-88d5-11ea-813c-0dbafcae81d0.png)

![image](https://user-images.githubusercontent.com/1280767/80440391-afadc000-88d6-11ea-8102-ccc344046640.png)

**Comment by jarad** [comment]
Investigating.

**Comment by jarad** [comment]
Got it. PR incoming
