### ISSUE TITLE
Automate team creation on GitHub

### ISSUE THREAD

**Issue by hannanabdul55** [reichlab/covid19-forecast-hub#960]
Automate the curation of the teams list on GitHub.

**Comment by mzorn-58** [comment]
@hannanabdul55  Is this completed?

**Comment by hannanabdul55** [comment]
No. I have not worked on this.

**Comment by nickreich** [comment]
I think  we should close this. we have a process to manually add the teams. it's not pretty but it's working, and the team list on the website is nicely automated.
