### ISSUE TITLE
Available implementation of weighted interval score?

### ISSUE THREAD

**Issue by jerome-white** [reichlab/covid19-forecast-hub#971]
I'd like to use the [weighted interval score](https://arxiv.org/abs/2005.12881) for evaluation of my own models. I've searched this repository, but can't seem to find an implementation. Does an open source implementation exist? If so, where can it be found?

**Comment by nickreich** [comment]
Hi @jerome-white.  thanks for the question. Here are a couple of options, depending on your use-case.  
 - for scoring forecasts not stored in our repo, I think the best option might be to use the scoringutils package, which has interval scores that you would need to aggregate into a weighted interval score: https://epiforecasts.io/scoringutils/ (they might consider adding a WIS metric if we asked nicely)
 - for forecasts in the repo already, scores are available from our Zoltar database: https://zoltardata.com/project/44/score_data
