### ISSUE TITLE
Add forecast_date, target_end_date to 2020-04-13 CU data-processed/ files

### ISSUE THREAD

**Issue by jarad** [reichlab/covid19-forecast-hub#99]
The following files need required fields `forecast_date` and `target_end_date`:

data-processed/CU-60contact/2020-04-13-CU-60contact.csv
data-processed/CU-70contact/2020-04-13-CU-70contact.csv
data-processed/CU-80contact/2020-04-13-CU-80contact.csv
data-processed/CU-nointerv/2020-04-13-CU-nointerv.csv

**Comment by jbracher** [comment]
These files are a relic from a time when files were processed and formatted differently. Initially we kept them for the record, but I think they can be removed to avoid confusion, correct @nickreich ?

**Comment by nickreich** [comment]
@jbracher what do you mean "there is no file for 13 April"? If we have these files already, can we not just add the additional columns as needed and keep them in the repo?

**Comment by jbracher** [comment]
Sorry, that was not very clear. CU did not issue forecasts on 13 April. That file comes from a time when the date in the file name was the time of forecast collection (by us), i.e. a Monday. The forecasts contained in the file from Monday 13 April are now contained in the file for Sunday 12 April, which is when CU issued the forecasts.

**Comment by nickreich** [comment]
Ok. I will delete the 4/13 files.
